/********************************************************************************
** Form generated from reading UI file 'mainwindowpToeFP.ui'
**
** Created by: Qt User Interface Compiler version 5.12.8
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef MAINWINDOWPTOEFP_H
#define MAINWINDOWPTOEFP_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QFrame>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QWidget>
#include "qcustomplot.h"

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QTabWidget *TW_MAIN;
    QWidget *TAB_ROBOT;
    QGroupBox *GB_MOTOR;
    QTableWidget *TB_MOTOR;
    QGroupBox *GB_IMU;
    QTableWidget *TW_IMU_RPY;
    QTableWidget *TW_IMU_GYRO;
    QTableWidget *TW_IMU_ACC;
    QGroupBox *GB_IP_ADDRESS;
    QLineEdit *TE_IP_ADDRESS;
    QPushButton *BT_IP_ADDRESS;
    QLabel *LB_IP_ADDRESS;
    QGroupBox *GB_RESTART;
    QPushButton *BT_ROBOT_RESTART;
    QCheckBox *CB_DEVELOPER_MODE;
    QWidget *TAB_CONTROL;
    QTabWidget *GAB_FOOT_TRAJ;
    QWidget *TAB_LINEAR;
    QCustomPlot *QCP_BODY_POS_Y;
    QCustomPlot *QCP_BODY_POS_Z;
    QCustomPlot *QCP_BODY_POS_X;
    QCustomPlot *QCP_BODY_VEL_X;
    QCustomPlot *QCP_BODY_VEL_Y;
    QCustomPlot *QCP_BODY_VEL_Z;
    QWidget *TAB_ANGULAR;
    QCustomPlot *QCP_BODY_ANG_POS_Y;
    QCustomPlot *QCP_BODY_ANG_POS_Z;
    QCustomPlot *QCP_BODY_ANG_POS_X;
    QCustomPlot *QCP_BODY_ANG_VEL_Y;
    QCustomPlot *QCP_BODY_ANG_VEL_Z;
    QCustomPlot *QCP_BODY_ANG_VEL_X;
    QWidget *TAB_MOTOR;
    QTabWidget *tabWidget_motor;
    QWidget *tab_motor_position;
    QCustomPlot *QCP_MT_POS_FLHP;
    QCustomPlot *QCP_MT_POS_HLHR;
    QCustomPlot *QCP_MT_POS_FRHP;
    QCustomPlot *QCP_MT_POS_FLHR;
    QCustomPlot *QCP_MT_POS_FRHR;
    QCustomPlot *QCP_MT_POS_HLHP;
    QCustomPlot *QCP_MT_POS_FRKP;
    QCustomPlot *QCP_MT_POS_FLKP;
    QCustomPlot *QCP_MT_POS_HLKP;
    QCustomPlot *QCP_MT_POS_HRKP;
    QCustomPlot *QCP_MT_POS_HRHP;
    QCustomPlot *QCP_MT_POS_HRHR;
    QLineEdit *LE_HIP_ROLL;
    QLineEdit *LE_HIP_PITCH;
    QLineEdit *LE_KNEE_PITCH;
    QLineEdit *LE_FL;
    QLineEdit *LE_FR;
    QLineEdit *LE_HL;
    QLineEdit *LE_HR;
    QWidget *tab_motor_velocity;
    QLineEdit *LE_HIP_ROLL_2;
    QCustomPlot *QCP_MT_VEL_FLHR;
    QCustomPlot *QCP_MT_VEL_HLHP;
    QCustomPlot *QCP_MT_VEL_HRKP;
    QCustomPlot *QCP_MT_VEL_FRHR;
    QLineEdit *LE_FL_2;
    QCustomPlot *QCP_MT_VEL_FRHP;
    QCustomPlot *QCP_MT_VEL_FRKP;
    QCustomPlot *QCP_MT_VEL_HLHR;
    QCustomPlot *QCP_MT_VEL_FLHP;
    QLineEdit *LE_HR_2;
    QCustomPlot *QCP_MT_VEL_FLKP;
    QCustomPlot *QCP_MT_VEL_HLKP;
    QLineEdit *LE_HL_2;
    QCustomPlot *QCP_MT_VEL_HRHP;
    QLineEdit *LE_FR_2;
    QLineEdit *LE_HIP_PITCH_2;
    QCustomPlot *QCP_MT_VEL_HRHR;
    QLineEdit *LE_KNEE_PITCH_2;
    QWidget *tab_motor_torque;
    QLineEdit *LE_KNEE_PITCH_3;
    QCustomPlot *QCP_MT_TAU_FRHP;
    QLineEdit *LE_HR_3;
    QCustomPlot *QCP_MT_TAU_FRKP;
    QCustomPlot *QCP_MT_TAU_FLHP;
    QLineEdit *LE_FL_3;
    QCustomPlot *QCP_MT_TAU_FLKP;
    QLineEdit *LE_HIP_PITCH_3;
    QCustomPlot *QCP_MT_TAU_FLHR;
    QCustomPlot *QCP_MT_TAU_HLHR;
    QCustomPlot *QCP_MT_TAU_HRHP;
    QCustomPlot *QCP_MT_TAU_FRHR;
    QCustomPlot *QCP_MT_TAU_HLHP;
    QLineEdit *LE_HIP_ROLL_3;
    QCustomPlot *QCP_MT_TAU_HRKP;
    QLineEdit *LE_FR_3;
    QCustomPlot *QCP_MT_TAU_HRHR;
    QLineEdit *LE_HL_3;
    QCustomPlot *QCP_MT_TAU_HLKP;
    QWidget *TAB_CONTACT;
    QCustomPlot *QCP_CONTACT_HR;
    QCustomPlot *QCP_CONTACT_FL;
    QCustomPlot *QCP_CONTACT_FR;
    QCustomPlot *QCP_CONTACT_HL;
    QWidget *TAB_CONSOLE;
    QLineEdit *LE_JOYSTICK_LB;
    QLabel *label_joystick_right_y;
    QLineEdit *LE_JOYSTICK_UP;
    QLineEdit *LE_JOYSTICK_B;
    QCustomPlot *QCP_JOYSTICK_LEFT;
    QLineEdit *LE_JOYSTICK_RIGHT;
    QLineEdit *LE_JOYSTICK_A;
    QLineEdit *LE_JOYSTICK_RIGHT_Y;
    QLabel *label_joystick_left_y;
    QLabel *label_joystick_left_x;
    QLineEdit *LE_JOYSTICK_LT;
    QLineEdit *LE_JOYSTICK_RT;
    QLabel *label_joystick_right_x;
    QCustomPlot *QCP_JOYSTICK_RIGHT;
    QLineEdit *LE_JOYSTICK_Y;
    QLineEdit *LE_JOYSTICK_X;
    QLineEdit *LE_JOYSTICK_LEFT_Y;
    QLineEdit *LE_JOYSTICK_START;
    QLineEdit *LE_JOYSTICK_RIGHT_X;
    QLineEdit *LE_JOYSTICK_DOWN;
    QLineEdit *LE_JOYSTICK_RB;
    QLineEdit *LE_JOYSTICK_LEFT;
    QLineEdit *LE_JOYSTICK_LEFT_X;
    QLineEdit *LE_CONSOLE_NAME;
    QLineEdit *LE_CONSOLE_NAME_2;
    QWidget *WG_TOP;
    QPushButton *BT_QUIT;
    QPushButton *BT_SCALE_UP;
    QPushButton *BT_MINIMIZE;
    QWidget *WG_ROBOT_STATE;
    QFrame *FR_ROBOT_STATE;
    QGroupBox *GB_ROBOR_STATE;
    QLineEdit *LE_CONNECT_1;
    QLineEdit *LE_ROBOT_STATE;
    QLineEdit *LE_CONNECT_2;
    QLabel *LB_IMG_CAMEL;
    QPushButton *BT_ROBOT_START;
    QGroupBox *GB_GRAPH_OPTION;
    QPushButton *BT_GRAPH_RESET;
    QPushButton *BT_GRAPH_UP;
    QPushButton *BT_GRAPH_DOWN;
    QPushButton *BT_GRAPH_PAUSE_GRAPH;
    QGroupBox *GB_CONTROL_BT;
    QGroupBox *GB_HOME_MOTION;
    QPushButton *BT_SIT_DOWN;
    QPushButton *BT_STAND_UP;
    QGroupBox *GB_TROT_MODE;
    QLineEdit *LE_TROT_OVERLAP;
    QPushButton *BT_TROT_SLOW;
    QLineEdit *LE_TROT_FAST;
    QLineEdit *LE_TROT_SLOW;
    QPushButton *BT_TROT_FAST;
    QPushButton *BT_TROT_OVERLAP;
    QPushButton *BT_TROT_STOP;
    QLineEdit *LE_TROT_STOP;
    QPushButton *BT_E_STOP;
    QLineEdit *LE_STUMBLE;
    QLabel *L_STUMBLE;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(1280, 800);
        MainWindow->setMinimumSize(QSize(1280, 600));
        MainWindow->setMaximumSize(QSize(1280, 800));
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        TW_MAIN = new QTabWidget(centralwidget);
        TW_MAIN->setObjectName(QString::fromUtf8("TW_MAIN"));
        TW_MAIN->setGeometry(QRect(400, 100, 871, 651));
        QFont font;
        font.setPointSize(12);
        TW_MAIN->setFont(font);
        TAB_ROBOT = new QWidget();
        TAB_ROBOT->setObjectName(QString::fromUtf8("TAB_ROBOT"));
        GB_MOTOR = new QGroupBox(TAB_ROBOT);
        GB_MOTOR->setObjectName(QString::fromUtf8("GB_MOTOR"));
        GB_MOTOR->setGeometry(QRect(9, 9, 518, 401));
        QFont font1;
        font1.setPointSize(9);
        GB_MOTOR->setFont(font1);
        TB_MOTOR = new QTableWidget(GB_MOTOR);
        if (TB_MOTOR->columnCount() < 6)
            TB_MOTOR->setColumnCount(6);
        QFont font2;
        font2.setPointSize(9);
        font2.setBold(true);
        font2.setWeight(75);
        QTableWidgetItem *__qtablewidgetitem = new QTableWidgetItem();
        __qtablewidgetitem->setFont(font2);
        TB_MOTOR->setHorizontalHeaderItem(0, __qtablewidgetitem);
        QTableWidgetItem *__qtablewidgetitem1 = new QTableWidgetItem();
        __qtablewidgetitem1->setFont(font2);
        TB_MOTOR->setHorizontalHeaderItem(1, __qtablewidgetitem1);
        QTableWidgetItem *__qtablewidgetitem2 = new QTableWidgetItem();
        __qtablewidgetitem2->setFont(font2);
        TB_MOTOR->setHorizontalHeaderItem(2, __qtablewidgetitem2);
        QTableWidgetItem *__qtablewidgetitem3 = new QTableWidgetItem();
        __qtablewidgetitem3->setFont(font2);
        TB_MOTOR->setHorizontalHeaderItem(3, __qtablewidgetitem3);
        QTableWidgetItem *__qtablewidgetitem4 = new QTableWidgetItem();
        __qtablewidgetitem4->setFont(font2);
        TB_MOTOR->setHorizontalHeaderItem(4, __qtablewidgetitem4);
        QTableWidgetItem *__qtablewidgetitem5 = new QTableWidgetItem();
        __qtablewidgetitem5->setFont(font2);
        TB_MOTOR->setHorizontalHeaderItem(5, __qtablewidgetitem5);
        if (TB_MOTOR->rowCount() < 12)
            TB_MOTOR->setRowCount(12);
        QTableWidgetItem *__qtablewidgetitem6 = new QTableWidgetItem();
        __qtablewidgetitem6->setFont(font2);
        TB_MOTOR->setVerticalHeaderItem(0, __qtablewidgetitem6);
        QTableWidgetItem *__qtablewidgetitem7 = new QTableWidgetItem();
        __qtablewidgetitem7->setFont(font2);
        TB_MOTOR->setVerticalHeaderItem(1, __qtablewidgetitem7);
        QTableWidgetItem *__qtablewidgetitem8 = new QTableWidgetItem();
        __qtablewidgetitem8->setFont(font2);
        TB_MOTOR->setVerticalHeaderItem(2, __qtablewidgetitem8);
        QTableWidgetItem *__qtablewidgetitem9 = new QTableWidgetItem();
        __qtablewidgetitem9->setFont(font2);
        TB_MOTOR->setVerticalHeaderItem(3, __qtablewidgetitem9);
        QTableWidgetItem *__qtablewidgetitem10 = new QTableWidgetItem();
        __qtablewidgetitem10->setFont(font2);
        TB_MOTOR->setVerticalHeaderItem(4, __qtablewidgetitem10);
        QTableWidgetItem *__qtablewidgetitem11 = new QTableWidgetItem();
        __qtablewidgetitem11->setFont(font2);
        TB_MOTOR->setVerticalHeaderItem(5, __qtablewidgetitem11);
        QTableWidgetItem *__qtablewidgetitem12 = new QTableWidgetItem();
        __qtablewidgetitem12->setFont(font2);
        TB_MOTOR->setVerticalHeaderItem(6, __qtablewidgetitem12);
        QTableWidgetItem *__qtablewidgetitem13 = new QTableWidgetItem();
        __qtablewidgetitem13->setFont(font2);
        TB_MOTOR->setVerticalHeaderItem(7, __qtablewidgetitem13);
        QTableWidgetItem *__qtablewidgetitem14 = new QTableWidgetItem();
        __qtablewidgetitem14->setFont(font2);
        TB_MOTOR->setVerticalHeaderItem(8, __qtablewidgetitem14);
        QTableWidgetItem *__qtablewidgetitem15 = new QTableWidgetItem();
        __qtablewidgetitem15->setFont(font2);
        TB_MOTOR->setVerticalHeaderItem(9, __qtablewidgetitem15);
        QTableWidgetItem *__qtablewidgetitem16 = new QTableWidgetItem();
        __qtablewidgetitem16->setFont(font2);
        TB_MOTOR->setVerticalHeaderItem(10, __qtablewidgetitem16);
        QTableWidgetItem *__qtablewidgetitem17 = new QTableWidgetItem();
        __qtablewidgetitem17->setFont(font2);
        TB_MOTOR->setVerticalHeaderItem(11, __qtablewidgetitem17);
        QFont font3;
        font3.setPointSize(11);
        QTableWidgetItem *__qtablewidgetitem18 = new QTableWidgetItem();
        __qtablewidgetitem18->setFont(font3);
        TB_MOTOR->setItem(0, 0, __qtablewidgetitem18);
        TB_MOTOR->setObjectName(QString::fromUtf8("TB_MOTOR"));
        TB_MOTOR->setGeometry(QRect(1, 19, 517, 383));
        TB_MOTOR->setFont(font1);
        TB_MOTOR->setGridStyle(Qt::SolidLine);
        TB_MOTOR->setSortingEnabled(false);
        TB_MOTOR->setWordWrap(true);
        TB_MOTOR->setCornerButtonEnabled(true);
        TB_MOTOR->horizontalHeader()->setMinimumSectionSize(45);
        TB_MOTOR->horizontalHeader()->setDefaultSectionSize(79);
        TB_MOTOR->verticalHeader()->setDefaultSectionSize(29);
        GB_IMU = new QGroupBox(TAB_ROBOT);
        GB_IMU->setObjectName(QString::fromUtf8("GB_IMU"));
        GB_IMU->setGeometry(QRect(540, 10, 321, 171));
        GB_IMU->setFont(font1);
        TW_IMU_RPY = new QTableWidget(GB_IMU);
        if (TW_IMU_RPY->columnCount() < 3)
            TW_IMU_RPY->setColumnCount(3);
        QTableWidgetItem *__qtablewidgetitem19 = new QTableWidgetItem();
        __qtablewidgetitem19->setFont(font2);
        TW_IMU_RPY->setHorizontalHeaderItem(0, __qtablewidgetitem19);
        QTableWidgetItem *__qtablewidgetitem20 = new QTableWidgetItem();
        __qtablewidgetitem20->setFont(font2);
        TW_IMU_RPY->setHorizontalHeaderItem(1, __qtablewidgetitem20);
        QTableWidgetItem *__qtablewidgetitem21 = new QTableWidgetItem();
        __qtablewidgetitem21->setFont(font2);
        TW_IMU_RPY->setHorizontalHeaderItem(2, __qtablewidgetitem21);
        if (TW_IMU_RPY->rowCount() < 1)
            TW_IMU_RPY->setRowCount(1);
        QTableWidgetItem *__qtablewidgetitem22 = new QTableWidgetItem();
        __qtablewidgetitem22->setFont(font2);
        TW_IMU_RPY->setVerticalHeaderItem(0, __qtablewidgetitem22);
        TW_IMU_RPY->setObjectName(QString::fromUtf8("TW_IMU_RPY"));
        TW_IMU_RPY->setGeometry(QRect(1, 18, 318, 53));
        TW_IMU_RPY->horizontalHeader()->setDefaultSectionSize(92);
        TW_IMU_RPY->verticalHeader()->setDefaultSectionSize(34);
        TW_IMU_GYRO = new QTableWidget(GB_IMU);
        if (TW_IMU_GYRO->columnCount() < 3)
            TW_IMU_GYRO->setColumnCount(3);
        QTableWidgetItem *__qtablewidgetitem23 = new QTableWidgetItem();
        __qtablewidgetitem23->setFont(font2);
        TW_IMU_GYRO->setHorizontalHeaderItem(0, __qtablewidgetitem23);
        QTableWidgetItem *__qtablewidgetitem24 = new QTableWidgetItem();
        __qtablewidgetitem24->setFont(font2);
        TW_IMU_GYRO->setHorizontalHeaderItem(1, __qtablewidgetitem24);
        QTableWidgetItem *__qtablewidgetitem25 = new QTableWidgetItem();
        __qtablewidgetitem25->setFont(font2);
        TW_IMU_GYRO->setHorizontalHeaderItem(2, __qtablewidgetitem25);
        if (TW_IMU_GYRO->rowCount() < 1)
            TW_IMU_GYRO->setRowCount(1);
        QTableWidgetItem *__qtablewidgetitem26 = new QTableWidgetItem();
        __qtablewidgetitem26->setFont(font2);
        TW_IMU_GYRO->setVerticalHeaderItem(0, __qtablewidgetitem26);
        TW_IMU_GYRO->setObjectName(QString::fromUtf8("TW_IMU_GYRO"));
        TW_IMU_GYRO->setGeometry(QRect(0, 70, 319, 51));
        TW_IMU_GYRO->horizontalHeader()->setDefaultSectionSize(92);
        TW_IMU_GYRO->verticalHeader()->setDefaultSectionSize(34);
        TW_IMU_ACC = new QTableWidget(GB_IMU);
        if (TW_IMU_ACC->columnCount() < 3)
            TW_IMU_ACC->setColumnCount(3);
        QTableWidgetItem *__qtablewidgetitem27 = new QTableWidgetItem();
        __qtablewidgetitem27->setFont(font2);
        TW_IMU_ACC->setHorizontalHeaderItem(0, __qtablewidgetitem27);
        QTableWidgetItem *__qtablewidgetitem28 = new QTableWidgetItem();
        __qtablewidgetitem28->setFont(font2);
        TW_IMU_ACC->setHorizontalHeaderItem(1, __qtablewidgetitem28);
        QTableWidgetItem *__qtablewidgetitem29 = new QTableWidgetItem();
        __qtablewidgetitem29->setFont(font2);
        TW_IMU_ACC->setHorizontalHeaderItem(2, __qtablewidgetitem29);
        if (TW_IMU_ACC->rowCount() < 1)
            TW_IMU_ACC->setRowCount(1);
        QTableWidgetItem *__qtablewidgetitem30 = new QTableWidgetItem();
        __qtablewidgetitem30->setFont(font2);
        TW_IMU_ACC->setVerticalHeaderItem(0, __qtablewidgetitem30);
        TW_IMU_ACC->setObjectName(QString::fromUtf8("TW_IMU_ACC"));
        TW_IMU_ACC->setGeometry(QRect(1, 120, 318, 51));
        TW_IMU_ACC->horizontalHeader()->setDefaultSectionSize(92);
        TW_IMU_ACC->verticalHeader()->setDefaultSectionSize(34);
        GB_IP_ADDRESS = new QGroupBox(TAB_ROBOT);
        GB_IP_ADDRESS->setObjectName(QString::fromUtf8("GB_IP_ADDRESS"));
        GB_IP_ADDRESS->setGeometry(QRect(540, 200, 321, 71));
        GB_IP_ADDRESS->setFont(font1);
        TE_IP_ADDRESS = new QLineEdit(GB_IP_ADDRESS);
        TE_IP_ADDRESS->setObjectName(QString::fromUtf8("TE_IP_ADDRESS"));
        TE_IP_ADDRESS->setGeometry(QRect(7, 24, 221, 26));
        BT_IP_ADDRESS = new QPushButton(GB_IP_ADDRESS);
        BT_IP_ADDRESS->setObjectName(QString::fromUtf8("BT_IP_ADDRESS"));
        BT_IP_ADDRESS->setGeometry(QRect(237, 24, 78, 26));
        LB_IP_ADDRESS = new QLabel(GB_IP_ADDRESS);
        LB_IP_ADDRESS->setObjectName(QString::fromUtf8("LB_IP_ADDRESS"));
        LB_IP_ADDRESS->setGeometry(QRect(6, 52, 310, 19));
        LB_IP_ADDRESS->setFont(font1);
        GB_RESTART = new QGroupBox(TAB_ROBOT);
        GB_RESTART->setObjectName(QString::fromUtf8("GB_RESTART"));
        GB_RESTART->setGeometry(QRect(633, 332, 131, 136));
        QFont font4;
        font4.setPointSize(12);
        font4.setBold(true);
        font4.setItalic(false);
        font4.setWeight(75);
        GB_RESTART->setFont(font4);
        BT_ROBOT_RESTART = new QPushButton(GB_RESTART);
        BT_ROBOT_RESTART->setObjectName(QString::fromUtf8("BT_ROBOT_RESTART"));
        BT_ROBOT_RESTART->setGeometry(QRect(14, 37, 104, 84));
        QFont font5;
        font5.setPointSize(12);
        font5.setBold(false);
        font5.setItalic(false);
        font5.setUnderline(false);
        font5.setWeight(50);
        BT_ROBOT_RESTART->setFont(font5);
        CB_DEVELOPER_MODE = new QCheckBox(TAB_ROBOT);
        CB_DEVELOPER_MODE->setObjectName(QString::fromUtf8("CB_DEVELOPER_MODE"));
        CB_DEVELOPER_MODE->setGeometry(QRect(709, 540, 151, 58));
        QFont font6;
        font6.setPointSize(12);
        font6.setBold(true);
        font6.setWeight(75);
        CB_DEVELOPER_MODE->setFont(font6);
        CB_DEVELOPER_MODE->setStyleSheet(QString::fromUtf8("QCheckBox::indicator {width: 40px; height: 40px}"));
        CB_DEVELOPER_MODE->setIconSize(QSize(32, 32));
        TW_MAIN->addTab(TAB_ROBOT, QString());
        TAB_CONTROL = new QWidget();
        TAB_CONTROL->setObjectName(QString::fromUtf8("TAB_CONTROL"));
        GAB_FOOT_TRAJ = new QTabWidget(TAB_CONTROL);
        GAB_FOOT_TRAJ->setObjectName(QString::fromUtf8("GAB_FOOT_TRAJ"));
        GAB_FOOT_TRAJ->setGeometry(QRect(-2, -1, 871, 621));
        GAB_FOOT_TRAJ->setFont(font);
        GAB_FOOT_TRAJ->setLayoutDirection(Qt::LeftToRight);
        GAB_FOOT_TRAJ->setTabPosition(QTabWidget::West);
        TAB_LINEAR = new QWidget();
        TAB_LINEAR->setObjectName(QString::fromUtf8("TAB_LINEAR"));
        QCP_BODY_POS_Y = new QCustomPlot(TAB_LINEAR);
        QCP_BODY_POS_Y->setObjectName(QString::fromUtf8("QCP_BODY_POS_Y"));
        QCP_BODY_POS_Y->setGeometry(QRect(13, 210, 401, 191));
        QCP_BODY_POS_Z = new QCustomPlot(TAB_LINEAR);
        QCP_BODY_POS_Z->setObjectName(QString::fromUtf8("QCP_BODY_POS_Z"));
        QCP_BODY_POS_Z->setGeometry(QRect(13, 410, 401, 191));
        QCP_BODY_POS_X = new QCustomPlot(TAB_LINEAR);
        QCP_BODY_POS_X->setObjectName(QString::fromUtf8("QCP_BODY_POS_X"));
        QCP_BODY_POS_X->setGeometry(QRect(13, 10, 401, 191));
        QCP_BODY_VEL_X = new QCustomPlot(TAB_LINEAR);
        QCP_BODY_VEL_X->setObjectName(QString::fromUtf8("QCP_BODY_VEL_X"));
        QCP_BODY_VEL_X->setGeometry(QRect(419, 10, 401, 191));
        QCP_BODY_VEL_Y = new QCustomPlot(TAB_LINEAR);
        QCP_BODY_VEL_Y->setObjectName(QString::fromUtf8("QCP_BODY_VEL_Y"));
        QCP_BODY_VEL_Y->setGeometry(QRect(419, 210, 401, 191));
        QCP_BODY_VEL_Z = new QCustomPlot(TAB_LINEAR);
        QCP_BODY_VEL_Z->setObjectName(QString::fromUtf8("QCP_BODY_VEL_Z"));
        QCP_BODY_VEL_Z->setGeometry(QRect(419, 410, 401, 191));
        GAB_FOOT_TRAJ->addTab(TAB_LINEAR, QString());
        TAB_ANGULAR = new QWidget();
        TAB_ANGULAR->setObjectName(QString::fromUtf8("TAB_ANGULAR"));
        QCP_BODY_ANG_POS_Y = new QCustomPlot(TAB_ANGULAR);
        QCP_BODY_ANG_POS_Y->setObjectName(QString::fromUtf8("QCP_BODY_ANG_POS_Y"));
        QCP_BODY_ANG_POS_Y->setGeometry(QRect(13, 210, 401, 191));
        QCP_BODY_ANG_POS_Z = new QCustomPlot(TAB_ANGULAR);
        QCP_BODY_ANG_POS_Z->setObjectName(QString::fromUtf8("QCP_BODY_ANG_POS_Z"));
        QCP_BODY_ANG_POS_Z->setGeometry(QRect(13, 410, 401, 191));
        QCP_BODY_ANG_POS_X = new QCustomPlot(TAB_ANGULAR);
        QCP_BODY_ANG_POS_X->setObjectName(QString::fromUtf8("QCP_BODY_ANG_POS_X"));
        QCP_BODY_ANG_POS_X->setGeometry(QRect(13, 10, 401, 191));
        QCP_BODY_ANG_VEL_Y = new QCustomPlot(TAB_ANGULAR);
        QCP_BODY_ANG_VEL_Y->setObjectName(QString::fromUtf8("QCP_BODY_ANG_VEL_Y"));
        QCP_BODY_ANG_VEL_Y->setGeometry(QRect(419, 210, 401, 191));
        QCP_BODY_ANG_VEL_Z = new QCustomPlot(TAB_ANGULAR);
        QCP_BODY_ANG_VEL_Z->setObjectName(QString::fromUtf8("QCP_BODY_ANG_VEL_Z"));
        QCP_BODY_ANG_VEL_Z->setGeometry(QRect(419, 410, 401, 191));
        QCP_BODY_ANG_VEL_X = new QCustomPlot(TAB_ANGULAR);
        QCP_BODY_ANG_VEL_X->setObjectName(QString::fromUtf8("QCP_BODY_ANG_VEL_X"));
        QCP_BODY_ANG_VEL_X->setGeometry(QRect(419, 10, 401, 191));
        GAB_FOOT_TRAJ->addTab(TAB_ANGULAR, QString());
        TAB_MOTOR = new QWidget();
        TAB_MOTOR->setObjectName(QString::fromUtf8("TAB_MOTOR"));
        tabWidget_motor = new QTabWidget(TAB_MOTOR);
        tabWidget_motor->setObjectName(QString::fromUtf8("tabWidget_motor"));
        tabWidget_motor->setGeometry(QRect(0, 0, 833, 621));
        QSizePolicy sizePolicy(QSizePolicy::Expanding, QSizePolicy::Expanding);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(tabWidget_motor->sizePolicy().hasHeightForWidth());
        tabWidget_motor->setSizePolicy(sizePolicy);
        QFont font7;
        font7.setPointSize(12);
        font7.setKerning(true);
        tabWidget_motor->setFont(font7);
        tabWidget_motor->setStyleSheet(QString::fromUtf8(""));
        tabWidget_motor->setIconSize(QSize(16, 16));
        tab_motor_position = new QWidget();
        tab_motor_position->setObjectName(QString::fromUtf8("tab_motor_position"));
        QCP_MT_POS_FLHP = new QCustomPlot(tab_motor_position);
        QCP_MT_POS_FLHP->setObjectName(QString::fromUtf8("QCP_MT_POS_FLHP"));
        QCP_MT_POS_FLHP->setGeometry(QRect(305, 20, 255, 135));
        QCP_MT_POS_HLHR = new QCustomPlot(tab_motor_position);
        QCP_MT_POS_HLHR->setObjectName(QString::fromUtf8("QCP_MT_POS_HLHR"));
        QCP_MT_POS_HLHR->setGeometry(QRect(38, 305, 255, 135));
        QCP_MT_POS_FRHP = new QCustomPlot(tab_motor_position);
        QCP_MT_POS_FRHP->setObjectName(QString::fromUtf8("QCP_MT_POS_FRHP"));
        QCP_MT_POS_FRHP->setGeometry(QRect(305, 162, 255, 135));
        QCP_MT_POS_FLHR = new QCustomPlot(tab_motor_position);
        QCP_MT_POS_FLHR->setObjectName(QString::fromUtf8("QCP_MT_POS_FLHR"));
        QCP_MT_POS_FLHR->setGeometry(QRect(38, 20, 255, 135));
        QCP_MT_POS_FRHR = new QCustomPlot(tab_motor_position);
        QCP_MT_POS_FRHR->setObjectName(QString::fromUtf8("QCP_MT_POS_FRHR"));
        QCP_MT_POS_FRHR->setGeometry(QRect(38, 162, 255, 135));
        QCP_MT_POS_HLHP = new QCustomPlot(tab_motor_position);
        QCP_MT_POS_HLHP->setObjectName(QString::fromUtf8("QCP_MT_POS_HLHP"));
        QCP_MT_POS_HLHP->setGeometry(QRect(305, 305, 255, 135));
        QCP_MT_POS_FRKP = new QCustomPlot(tab_motor_position);
        QCP_MT_POS_FRKP->setObjectName(QString::fromUtf8("QCP_MT_POS_FRKP"));
        QCP_MT_POS_FRKP->setGeometry(QRect(569, 162, 255, 135));
        QCP_MT_POS_FLKP = new QCustomPlot(tab_motor_position);
        QCP_MT_POS_FLKP->setObjectName(QString::fromUtf8("QCP_MT_POS_FLKP"));
        QCP_MT_POS_FLKP->setGeometry(QRect(569, 20, 255, 135));
        QCP_MT_POS_HLKP = new QCustomPlot(tab_motor_position);
        QCP_MT_POS_HLKP->setObjectName(QString::fromUtf8("QCP_MT_POS_HLKP"));
        QCP_MT_POS_HLKP->setGeometry(QRect(569, 305, 255, 135));
        QCP_MT_POS_HRKP = new QCustomPlot(tab_motor_position);
        QCP_MT_POS_HRKP->setObjectName(QString::fromUtf8("QCP_MT_POS_HRKP"));
        QCP_MT_POS_HRKP->setGeometry(QRect(569, 448, 255, 135));
        QCP_MT_POS_HRHP = new QCustomPlot(tab_motor_position);
        QCP_MT_POS_HRHP->setObjectName(QString::fromUtf8("QCP_MT_POS_HRHP"));
        QCP_MT_POS_HRHP->setGeometry(QRect(305, 448, 255, 135));
        QCP_MT_POS_HRHR = new QCustomPlot(tab_motor_position);
        QCP_MT_POS_HRHR->setObjectName(QString::fromUtf8("QCP_MT_POS_HRHR"));
        QCP_MT_POS_HRHR->setGeometry(QRect(38, 448, 255, 135));
        LE_HIP_ROLL = new QLineEdit(tab_motor_position);
        LE_HIP_ROLL->setObjectName(QString::fromUtf8("LE_HIP_ROLL"));
        LE_HIP_ROLL->setGeometry(QRect(38, 3, 255, 15));
        sizePolicy.setHeightForWidth(LE_HIP_ROLL->sizePolicy().hasHeightForWidth());
        LE_HIP_ROLL->setSizePolicy(sizePolicy);
        LE_HIP_ROLL->setFont(font2);
        LE_HIP_ROLL->setMouseTracking(false);
        LE_HIP_ROLL->setAlignment(Qt::AlignCenter);
        LE_HIP_ROLL->setReadOnly(true);
        LE_HIP_PITCH = new QLineEdit(tab_motor_position);
        LE_HIP_PITCH->setObjectName(QString::fromUtf8("LE_HIP_PITCH"));
        LE_HIP_PITCH->setGeometry(QRect(305, 3, 255, 15));
        sizePolicy.setHeightForWidth(LE_HIP_PITCH->sizePolicy().hasHeightForWidth());
        LE_HIP_PITCH->setSizePolicy(sizePolicy);
        LE_HIP_PITCH->setFont(font2);
        LE_HIP_PITCH->setMouseTracking(false);
        LE_HIP_PITCH->setAlignment(Qt::AlignCenter);
        LE_HIP_PITCH->setReadOnly(true);
        LE_KNEE_PITCH = new QLineEdit(tab_motor_position);
        LE_KNEE_PITCH->setObjectName(QString::fromUtf8("LE_KNEE_PITCH"));
        LE_KNEE_PITCH->setGeometry(QRect(569, 3, 255, 15));
        sizePolicy.setHeightForWidth(LE_KNEE_PITCH->sizePolicy().hasHeightForWidth());
        LE_KNEE_PITCH->setSizePolicy(sizePolicy);
        LE_KNEE_PITCH->setFont(font2);
        LE_KNEE_PITCH->setMouseTracking(false);
        LE_KNEE_PITCH->setAlignment(Qt::AlignCenter);
        LE_KNEE_PITCH->setReadOnly(true);
        LE_FL = new QLineEdit(tab_motor_position);
        LE_FL->setObjectName(QString::fromUtf8("LE_FL"));
        LE_FL->setGeometry(QRect(5, 20, 26, 135));
        sizePolicy.setHeightForWidth(LE_FL->sizePolicy().hasHeightForWidth());
        LE_FL->setSizePolicy(sizePolicy);
        QFont font8;
        font8.setPointSize(9);
        font8.setBold(true);
        font8.setItalic(false);
        font8.setUnderline(false);
        font8.setWeight(75);
        font8.setKerning(false);
        LE_FL->setFont(font8);
        LE_FL->setMouseTracking(false);
        LE_FL->setLayoutDirection(Qt::LeftToRight);
        LE_FL->setAutoFillBackground(false);
        LE_FL->setCursorPosition(2);
        LE_FL->setAlignment(Qt::AlignCenter);
        LE_FL->setReadOnly(true);
        LE_FL->setClearButtonEnabled(false);
        LE_FR = new QLineEdit(tab_motor_position);
        LE_FR->setObjectName(QString::fromUtf8("LE_FR"));
        LE_FR->setGeometry(QRect(5, 162, 26, 135));
        sizePolicy.setHeightForWidth(LE_FR->sizePolicy().hasHeightForWidth());
        LE_FR->setSizePolicy(sizePolicy);
        LE_FR->setFont(font8);
        LE_FR->setMouseTracking(false);
        LE_FR->setLayoutDirection(Qt::LeftToRight);
        LE_FR->setAutoFillBackground(false);
        LE_FR->setAlignment(Qt::AlignCenter);
        LE_FR->setReadOnly(true);
        LE_FR->setClearButtonEnabled(false);
        LE_HL = new QLineEdit(tab_motor_position);
        LE_HL->setObjectName(QString::fromUtf8("LE_HL"));
        LE_HL->setGeometry(QRect(5, 305, 26, 135));
        sizePolicy.setHeightForWidth(LE_HL->sizePolicy().hasHeightForWidth());
        LE_HL->setSizePolicy(sizePolicy);
        LE_HL->setFont(font8);
        LE_HL->setMouseTracking(false);
        LE_HL->setLayoutDirection(Qt::LeftToRight);
        LE_HL->setAutoFillBackground(false);
        LE_HL->setAlignment(Qt::AlignCenter);
        LE_HL->setReadOnly(true);
        LE_HL->setClearButtonEnabled(false);
        LE_HR = new QLineEdit(tab_motor_position);
        LE_HR->setObjectName(QString::fromUtf8("LE_HR"));
        LE_HR->setGeometry(QRect(5, 448, 26, 135));
        sizePolicy.setHeightForWidth(LE_HR->sizePolicy().hasHeightForWidth());
        LE_HR->setSizePolicy(sizePolicy);
        LE_HR->setFont(font8);
        LE_HR->setMouseTracking(false);
        LE_HR->setLayoutDirection(Qt::LeftToRight);
        LE_HR->setAutoFillBackground(false);
        LE_HR->setAlignment(Qt::AlignCenter);
        LE_HR->setReadOnly(true);
        LE_HR->setClearButtonEnabled(false);
        tabWidget_motor->addTab(tab_motor_position, QString());
        tab_motor_velocity = new QWidget();
        tab_motor_velocity->setObjectName(QString::fromUtf8("tab_motor_velocity"));
        LE_HIP_ROLL_2 = new QLineEdit(tab_motor_velocity);
        LE_HIP_ROLL_2->setObjectName(QString::fromUtf8("LE_HIP_ROLL_2"));
        LE_HIP_ROLL_2->setGeometry(QRect(38, 3, 255, 15));
        sizePolicy.setHeightForWidth(LE_HIP_ROLL_2->sizePolicy().hasHeightForWidth());
        LE_HIP_ROLL_2->setSizePolicy(sizePolicy);
        LE_HIP_ROLL_2->setFont(font2);
        LE_HIP_ROLL_2->setMouseTracking(false);
        LE_HIP_ROLL_2->setAlignment(Qt::AlignCenter);
        LE_HIP_ROLL_2->setReadOnly(true);
        QCP_MT_VEL_FLHR = new QCustomPlot(tab_motor_velocity);
        QCP_MT_VEL_FLHR->setObjectName(QString::fromUtf8("QCP_MT_VEL_FLHR"));
        QCP_MT_VEL_FLHR->setGeometry(QRect(38, 20, 255, 135));
        QCP_MT_VEL_HLHP = new QCustomPlot(tab_motor_velocity);
        QCP_MT_VEL_HLHP->setObjectName(QString::fromUtf8("QCP_MT_VEL_HLHP"));
        QCP_MT_VEL_HLHP->setGeometry(QRect(305, 305, 255, 135));
        QCP_MT_VEL_HRKP = new QCustomPlot(tab_motor_velocity);
        QCP_MT_VEL_HRKP->setObjectName(QString::fromUtf8("QCP_MT_VEL_HRKP"));
        QCP_MT_VEL_HRKP->setGeometry(QRect(569, 448, 255, 135));
        QCP_MT_VEL_FRHR = new QCustomPlot(tab_motor_velocity);
        QCP_MT_VEL_FRHR->setObjectName(QString::fromUtf8("QCP_MT_VEL_FRHR"));
        QCP_MT_VEL_FRHR->setGeometry(QRect(38, 162, 255, 135));
        LE_FL_2 = new QLineEdit(tab_motor_velocity);
        LE_FL_2->setObjectName(QString::fromUtf8("LE_FL_2"));
        LE_FL_2->setGeometry(QRect(5, 20, 26, 135));
        sizePolicy.setHeightForWidth(LE_FL_2->sizePolicy().hasHeightForWidth());
        LE_FL_2->setSizePolicy(sizePolicy);
        LE_FL_2->setFont(font8);
        LE_FL_2->setMouseTracking(false);
        LE_FL_2->setLayoutDirection(Qt::LeftToRight);
        LE_FL_2->setAutoFillBackground(false);
        LE_FL_2->setCursorPosition(2);
        LE_FL_2->setAlignment(Qt::AlignCenter);
        LE_FL_2->setReadOnly(true);
        LE_FL_2->setClearButtonEnabled(false);
        QCP_MT_VEL_FRHP = new QCustomPlot(tab_motor_velocity);
        QCP_MT_VEL_FRHP->setObjectName(QString::fromUtf8("QCP_MT_VEL_FRHP"));
        QCP_MT_VEL_FRHP->setGeometry(QRect(305, 162, 255, 135));
        QCP_MT_VEL_FRKP = new QCustomPlot(tab_motor_velocity);
        QCP_MT_VEL_FRKP->setObjectName(QString::fromUtf8("QCP_MT_VEL_FRKP"));
        QCP_MT_VEL_FRKP->setGeometry(QRect(569, 162, 255, 135));
        QCP_MT_VEL_HLHR = new QCustomPlot(tab_motor_velocity);
        QCP_MT_VEL_HLHR->setObjectName(QString::fromUtf8("QCP_MT_VEL_HLHR"));
        QCP_MT_VEL_HLHR->setGeometry(QRect(38, 305, 255, 135));
        QCP_MT_VEL_FLHP = new QCustomPlot(tab_motor_velocity);
        QCP_MT_VEL_FLHP->setObjectName(QString::fromUtf8("QCP_MT_VEL_FLHP"));
        QCP_MT_VEL_FLHP->setGeometry(QRect(305, 20, 255, 135));
        LE_HR_2 = new QLineEdit(tab_motor_velocity);
        LE_HR_2->setObjectName(QString::fromUtf8("LE_HR_2"));
        LE_HR_2->setGeometry(QRect(5, 448, 26, 135));
        sizePolicy.setHeightForWidth(LE_HR_2->sizePolicy().hasHeightForWidth());
        LE_HR_2->setSizePolicy(sizePolicy);
        LE_HR_2->setFont(font8);
        LE_HR_2->setMouseTracking(false);
        LE_HR_2->setLayoutDirection(Qt::LeftToRight);
        LE_HR_2->setAutoFillBackground(false);
        LE_HR_2->setAlignment(Qt::AlignCenter);
        LE_HR_2->setReadOnly(true);
        LE_HR_2->setClearButtonEnabled(false);
        QCP_MT_VEL_FLKP = new QCustomPlot(tab_motor_velocity);
        QCP_MT_VEL_FLKP->setObjectName(QString::fromUtf8("QCP_MT_VEL_FLKP"));
        QCP_MT_VEL_FLKP->setGeometry(QRect(569, 20, 255, 135));
        QCP_MT_VEL_HLKP = new QCustomPlot(tab_motor_velocity);
        QCP_MT_VEL_HLKP->setObjectName(QString::fromUtf8("QCP_MT_VEL_HLKP"));
        QCP_MT_VEL_HLKP->setGeometry(QRect(569, 305, 255, 135));
        LE_HL_2 = new QLineEdit(tab_motor_velocity);
        LE_HL_2->setObjectName(QString::fromUtf8("LE_HL_2"));
        LE_HL_2->setGeometry(QRect(5, 305, 26, 135));
        sizePolicy.setHeightForWidth(LE_HL_2->sizePolicy().hasHeightForWidth());
        LE_HL_2->setSizePolicy(sizePolicy);
        LE_HL_2->setFont(font8);
        LE_HL_2->setMouseTracking(false);
        LE_HL_2->setLayoutDirection(Qt::LeftToRight);
        LE_HL_2->setAutoFillBackground(false);
        LE_HL_2->setAlignment(Qt::AlignCenter);
        LE_HL_2->setReadOnly(true);
        LE_HL_2->setClearButtonEnabled(false);
        QCP_MT_VEL_HRHP = new QCustomPlot(tab_motor_velocity);
        QCP_MT_VEL_HRHP->setObjectName(QString::fromUtf8("QCP_MT_VEL_HRHP"));
        QCP_MT_VEL_HRHP->setGeometry(QRect(305, 448, 255, 135));
        LE_FR_2 = new QLineEdit(tab_motor_velocity);
        LE_FR_2->setObjectName(QString::fromUtf8("LE_FR_2"));
        LE_FR_2->setGeometry(QRect(5, 162, 26, 135));
        sizePolicy.setHeightForWidth(LE_FR_2->sizePolicy().hasHeightForWidth());
        LE_FR_2->setSizePolicy(sizePolicy);
        LE_FR_2->setFont(font8);
        LE_FR_2->setMouseTracking(false);
        LE_FR_2->setLayoutDirection(Qt::LeftToRight);
        LE_FR_2->setAutoFillBackground(false);
        LE_FR_2->setAlignment(Qt::AlignCenter);
        LE_FR_2->setReadOnly(true);
        LE_FR_2->setClearButtonEnabled(false);
        LE_HIP_PITCH_2 = new QLineEdit(tab_motor_velocity);
        LE_HIP_PITCH_2->setObjectName(QString::fromUtf8("LE_HIP_PITCH_2"));
        LE_HIP_PITCH_2->setGeometry(QRect(305, 3, 255, 15));
        sizePolicy.setHeightForWidth(LE_HIP_PITCH_2->sizePolicy().hasHeightForWidth());
        LE_HIP_PITCH_2->setSizePolicy(sizePolicy);
        LE_HIP_PITCH_2->setFont(font2);
        LE_HIP_PITCH_2->setMouseTracking(false);
        LE_HIP_PITCH_2->setAlignment(Qt::AlignCenter);
        LE_HIP_PITCH_2->setReadOnly(true);
        QCP_MT_VEL_HRHR = new QCustomPlot(tab_motor_velocity);
        QCP_MT_VEL_HRHR->setObjectName(QString::fromUtf8("QCP_MT_VEL_HRHR"));
        QCP_MT_VEL_HRHR->setGeometry(QRect(38, 448, 255, 135));
        LE_KNEE_PITCH_2 = new QLineEdit(tab_motor_velocity);
        LE_KNEE_PITCH_2->setObjectName(QString::fromUtf8("LE_KNEE_PITCH_2"));
        LE_KNEE_PITCH_2->setGeometry(QRect(569, 3, 255, 15));
        sizePolicy.setHeightForWidth(LE_KNEE_PITCH_2->sizePolicy().hasHeightForWidth());
        LE_KNEE_PITCH_2->setSizePolicy(sizePolicy);
        LE_KNEE_PITCH_2->setFont(font2);
        LE_KNEE_PITCH_2->setMouseTracking(false);
        LE_KNEE_PITCH_2->setAlignment(Qt::AlignCenter);
        LE_KNEE_PITCH_2->setReadOnly(true);
        tabWidget_motor->addTab(tab_motor_velocity, QString());
        tab_motor_torque = new QWidget();
        tab_motor_torque->setObjectName(QString::fromUtf8("tab_motor_torque"));
        LE_KNEE_PITCH_3 = new QLineEdit(tab_motor_torque);
        LE_KNEE_PITCH_3->setObjectName(QString::fromUtf8("LE_KNEE_PITCH_3"));
        LE_KNEE_PITCH_3->setGeometry(QRect(569, 3, 255, 15));
        sizePolicy.setHeightForWidth(LE_KNEE_PITCH_3->sizePolicy().hasHeightForWidth());
        LE_KNEE_PITCH_3->setSizePolicy(sizePolicy);
        LE_KNEE_PITCH_3->setFont(font2);
        LE_KNEE_PITCH_3->setMouseTracking(false);
        LE_KNEE_PITCH_3->setAlignment(Qt::AlignCenter);
        LE_KNEE_PITCH_3->setReadOnly(true);
        QCP_MT_TAU_FRHP = new QCustomPlot(tab_motor_torque);
        QCP_MT_TAU_FRHP->setObjectName(QString::fromUtf8("QCP_MT_TAU_FRHP"));
        QCP_MT_TAU_FRHP->setGeometry(QRect(305, 162, 255, 135));
        LE_HR_3 = new QLineEdit(tab_motor_torque);
        LE_HR_3->setObjectName(QString::fromUtf8("LE_HR_3"));
        LE_HR_3->setGeometry(QRect(5, 448, 26, 135));
        sizePolicy.setHeightForWidth(LE_HR_3->sizePolicy().hasHeightForWidth());
        LE_HR_3->setSizePolicy(sizePolicy);
        LE_HR_3->setFont(font8);
        LE_HR_3->setMouseTracking(false);
        LE_HR_3->setLayoutDirection(Qt::LeftToRight);
        LE_HR_3->setAutoFillBackground(false);
        LE_HR_3->setAlignment(Qt::AlignCenter);
        LE_HR_3->setReadOnly(true);
        LE_HR_3->setClearButtonEnabled(false);
        QCP_MT_TAU_FRKP = new QCustomPlot(tab_motor_torque);
        QCP_MT_TAU_FRKP->setObjectName(QString::fromUtf8("QCP_MT_TAU_FRKP"));
        QCP_MT_TAU_FRKP->setGeometry(QRect(569, 162, 255, 135));
        QCP_MT_TAU_FLHP = new QCustomPlot(tab_motor_torque);
        QCP_MT_TAU_FLHP->setObjectName(QString::fromUtf8("QCP_MT_TAU_FLHP"));
        QCP_MT_TAU_FLHP->setGeometry(QRect(305, 20, 255, 135));
        LE_FL_3 = new QLineEdit(tab_motor_torque);
        LE_FL_3->setObjectName(QString::fromUtf8("LE_FL_3"));
        LE_FL_3->setGeometry(QRect(5, 20, 26, 135));
        sizePolicy.setHeightForWidth(LE_FL_3->sizePolicy().hasHeightForWidth());
        LE_FL_3->setSizePolicy(sizePolicy);
        LE_FL_3->setFont(font8);
        LE_FL_3->setMouseTracking(false);
        LE_FL_3->setLayoutDirection(Qt::LeftToRight);
        LE_FL_3->setAutoFillBackground(false);
        LE_FL_3->setCursorPosition(2);
        LE_FL_3->setAlignment(Qt::AlignCenter);
        LE_FL_3->setReadOnly(true);
        LE_FL_3->setClearButtonEnabled(false);
        QCP_MT_TAU_FLKP = new QCustomPlot(tab_motor_torque);
        QCP_MT_TAU_FLKP->setObjectName(QString::fromUtf8("QCP_MT_TAU_FLKP"));
        QCP_MT_TAU_FLKP->setGeometry(QRect(569, 20, 255, 135));
        LE_HIP_PITCH_3 = new QLineEdit(tab_motor_torque);
        LE_HIP_PITCH_3->setObjectName(QString::fromUtf8("LE_HIP_PITCH_3"));
        LE_HIP_PITCH_3->setGeometry(QRect(305, 3, 255, 15));
        sizePolicy.setHeightForWidth(LE_HIP_PITCH_3->sizePolicy().hasHeightForWidth());
        LE_HIP_PITCH_3->setSizePolicy(sizePolicy);
        LE_HIP_PITCH_3->setFont(font2);
        LE_HIP_PITCH_3->setMouseTracking(false);
        LE_HIP_PITCH_3->setAlignment(Qt::AlignCenter);
        LE_HIP_PITCH_3->setReadOnly(true);
        QCP_MT_TAU_FLHR = new QCustomPlot(tab_motor_torque);
        QCP_MT_TAU_FLHR->setObjectName(QString::fromUtf8("QCP_MT_TAU_FLHR"));
        QCP_MT_TAU_FLHR->setGeometry(QRect(38, 20, 255, 135));
        QCP_MT_TAU_HLHR = new QCustomPlot(tab_motor_torque);
        QCP_MT_TAU_HLHR->setObjectName(QString::fromUtf8("QCP_MT_TAU_HLHR"));
        QCP_MT_TAU_HLHR->setGeometry(QRect(38, 305, 255, 135));
        QCP_MT_TAU_HRHP = new QCustomPlot(tab_motor_torque);
        QCP_MT_TAU_HRHP->setObjectName(QString::fromUtf8("QCP_MT_TAU_HRHP"));
        QCP_MT_TAU_HRHP->setGeometry(QRect(305, 448, 255, 135));
        QCP_MT_TAU_FRHR = new QCustomPlot(tab_motor_torque);
        QCP_MT_TAU_FRHR->setObjectName(QString::fromUtf8("QCP_MT_TAU_FRHR"));
        QCP_MT_TAU_FRHR->setGeometry(QRect(38, 162, 255, 135));
        QCP_MT_TAU_HLHP = new QCustomPlot(tab_motor_torque);
        QCP_MT_TAU_HLHP->setObjectName(QString::fromUtf8("QCP_MT_TAU_HLHP"));
        QCP_MT_TAU_HLHP->setGeometry(QRect(305, 305, 255, 135));
        LE_HIP_ROLL_3 = new QLineEdit(tab_motor_torque);
        LE_HIP_ROLL_3->setObjectName(QString::fromUtf8("LE_HIP_ROLL_3"));
        LE_HIP_ROLL_3->setGeometry(QRect(38, 3, 255, 15));
        sizePolicy.setHeightForWidth(LE_HIP_ROLL_3->sizePolicy().hasHeightForWidth());
        LE_HIP_ROLL_3->setSizePolicy(sizePolicy);
        LE_HIP_ROLL_3->setFont(font2);
        LE_HIP_ROLL_3->setMouseTracking(false);
        LE_HIP_ROLL_3->setAlignment(Qt::AlignCenter);
        LE_HIP_ROLL_3->setReadOnly(true);
        QCP_MT_TAU_HRKP = new QCustomPlot(tab_motor_torque);
        QCP_MT_TAU_HRKP->setObjectName(QString::fromUtf8("QCP_MT_TAU_HRKP"));
        QCP_MT_TAU_HRKP->setGeometry(QRect(569, 448, 255, 135));
        LE_FR_3 = new QLineEdit(tab_motor_torque);
        LE_FR_3->setObjectName(QString::fromUtf8("LE_FR_3"));
        LE_FR_3->setGeometry(QRect(5, 162, 26, 135));
        sizePolicy.setHeightForWidth(LE_FR_3->sizePolicy().hasHeightForWidth());
        LE_FR_3->setSizePolicy(sizePolicy);
        LE_FR_3->setFont(font8);
        LE_FR_3->setMouseTracking(false);
        LE_FR_3->setLayoutDirection(Qt::LeftToRight);
        LE_FR_3->setAutoFillBackground(false);
        LE_FR_3->setAlignment(Qt::AlignCenter);
        LE_FR_3->setReadOnly(true);
        LE_FR_3->setClearButtonEnabled(false);
        QCP_MT_TAU_HRHR = new QCustomPlot(tab_motor_torque);
        QCP_MT_TAU_HRHR->setObjectName(QString::fromUtf8("QCP_MT_TAU_HRHR"));
        QCP_MT_TAU_HRHR->setGeometry(QRect(38, 448, 255, 135));
        LE_HL_3 = new QLineEdit(tab_motor_torque);
        LE_HL_3->setObjectName(QString::fromUtf8("LE_HL_3"));
        LE_HL_3->setGeometry(QRect(5, 305, 26, 135));
        sizePolicy.setHeightForWidth(LE_HL_3->sizePolicy().hasHeightForWidth());
        LE_HL_3->setSizePolicy(sizePolicy);
        LE_HL_3->setFont(font8);
        LE_HL_3->setMouseTracking(false);
        LE_HL_3->setLayoutDirection(Qt::LeftToRight);
        LE_HL_3->setAutoFillBackground(false);
        LE_HL_3->setAlignment(Qt::AlignCenter);
        LE_HL_3->setReadOnly(true);
        LE_HL_3->setClearButtonEnabled(false);
        QCP_MT_TAU_HLKP = new QCustomPlot(tab_motor_torque);
        QCP_MT_TAU_HLKP->setObjectName(QString::fromUtf8("QCP_MT_TAU_HLKP"));
        QCP_MT_TAU_HLKP->setGeometry(QRect(569, 305, 255, 135));
        tabWidget_motor->addTab(tab_motor_torque, QString());
        GAB_FOOT_TRAJ->addTab(TAB_MOTOR, QString());
        TAB_CONTACT = new QWidget();
        TAB_CONTACT->setObjectName(QString::fromUtf8("TAB_CONTACT"));
        QCP_CONTACT_HR = new QCustomPlot(TAB_CONTACT);
        QCP_CONTACT_HR->setObjectName(QString::fromUtf8("QCP_CONTACT_HR"));
        QCP_CONTACT_HR->setGeometry(QRect(423, 311, 397, 300));
        QCP_CONTACT_FL = new QCustomPlot(TAB_CONTACT);
        QCP_CONTACT_FL->setObjectName(QString::fromUtf8("QCP_CONTACT_FL"));
        QCP_CONTACT_FL->setGeometry(QRect(20, 5, 397, 300));
        QCP_CONTACT_FR = new QCustomPlot(TAB_CONTACT);
        QCP_CONTACT_FR->setObjectName(QString::fromUtf8("QCP_CONTACT_FR"));
        QCP_CONTACT_FR->setGeometry(QRect(423, 5, 397, 300));
        QCP_CONTACT_HL = new QCustomPlot(TAB_CONTACT);
        QCP_CONTACT_HL->setObjectName(QString::fromUtf8("QCP_CONTACT_HL"));
        QCP_CONTACT_HL->setGeometry(QRect(20, 310, 397, 300));
        GAB_FOOT_TRAJ->addTab(TAB_CONTACT, QString());
        TW_MAIN->addTab(TAB_CONTROL, QString());
        TAB_CONSOLE = new QWidget();
        TAB_CONSOLE->setObjectName(QString::fromUtf8("TAB_CONSOLE"));
        LE_JOYSTICK_LB = new QLineEdit(TAB_CONSOLE);
        LE_JOYSTICK_LB->setObjectName(QString::fromUtf8("LE_JOYSTICK_LB"));
        LE_JOYSTICK_LB->setEnabled(false);
        LE_JOYSTICK_LB->setGeometry(QRect(111, 110, 130, 39));
        QFont font9;
        font9.setPointSize(15);
        LE_JOYSTICK_LB->setFont(font9);
        LE_JOYSTICK_LB->setFrame(true);
        LE_JOYSTICK_LB->setAlignment(Qt::AlignCenter);
        label_joystick_right_y = new QLabel(TAB_CONSOLE);
        label_joystick_right_y->setObjectName(QString::fromUtf8("label_joystick_right_y"));
        label_joystick_right_y->setGeometry(QRect(710, 585, 19, 19));
        label_joystick_right_y->setFont(font1);
        label_joystick_right_y->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        LE_JOYSTICK_UP = new QLineEdit(TAB_CONSOLE);
        LE_JOYSTICK_UP->setObjectName(QString::fromUtf8("LE_JOYSTICK_UP"));
        LE_JOYSTICK_UP->setEnabled(false);
        LE_JOYSTICK_UP->setGeometry(QRect(149, 188, 52, 52));
        LE_JOYSTICK_UP->setFont(font9);
        LE_JOYSTICK_UP->setFrame(true);
        LE_JOYSTICK_UP->setAlignment(Qt::AlignCenter);
        LE_JOYSTICK_B = new QLineEdit(TAB_CONSOLE);
        LE_JOYSTICK_B->setObjectName(QString::fromUtf8("LE_JOYSTICK_B"));
        LE_JOYSTICK_B->setEnabled(false);
        LE_JOYSTICK_B->setGeometry(QRect(743, 253, 52, 52));
        LE_JOYSTICK_B->setFont(font9);
        LE_JOYSTICK_B->setFrame(true);
        LE_JOYSTICK_B->setAlignment(Qt::AlignCenter);
        QCP_JOYSTICK_LEFT = new QCustomPlot(TAB_CONSOLE);
        QCP_JOYSTICK_LEFT->setObjectName(QString::fromUtf8("QCP_JOYSTICK_LEFT"));
        QCP_JOYSTICK_LEFT->setGeometry(QRect(79, 384, 195, 195));
        LE_JOYSTICK_RIGHT = new QLineEdit(TAB_CONSOLE);
        LE_JOYSTICK_RIGHT->setObjectName(QString::fromUtf8("LE_JOYSTICK_RIGHT"));
        LE_JOYSTICK_RIGHT->setEnabled(false);
        LE_JOYSTICK_RIGHT->setGeometry(QRect(215, 253, 52, 52));
        LE_JOYSTICK_RIGHT->setFont(font9);
        LE_JOYSTICK_RIGHT->setFrame(true);
        LE_JOYSTICK_RIGHT->setAlignment(Qt::AlignCenter);
        LE_JOYSTICK_A = new QLineEdit(TAB_CONSOLE);
        LE_JOYSTICK_A->setObjectName(QString::fromUtf8("LE_JOYSTICK_A"));
        LE_JOYSTICK_A->setEnabled(false);
        LE_JOYSTICK_A->setGeometry(QRect(677, 318, 52, 52));
        LE_JOYSTICK_A->setFont(font9);
        LE_JOYSTICK_A->setFrame(true);
        LE_JOYSTICK_A->setAlignment(Qt::AlignCenter);
        LE_JOYSTICK_RIGHT_Y = new QLineEdit(TAB_CONSOLE);
        LE_JOYSTICK_RIGHT_Y->setObjectName(QString::fromUtf8("LE_JOYSTICK_RIGHT_Y"));
        LE_JOYSTICK_RIGHT_Y->setEnabled(false);
        LE_JOYSTICK_RIGHT_Y->setGeometry(QRect(730, 585, 71, 19));
        LE_JOYSTICK_RIGHT_Y->setMinimumSize(QSize(0, 0));
        LE_JOYSTICK_RIGHT_Y->setMaximumSize(QSize(580, 200));
        LE_JOYSTICK_RIGHT_Y->setFont(font1);
        LE_JOYSTICK_RIGHT_Y->setAlignment(Qt::AlignCenter);
        label_joystick_left_y = new QLabel(TAB_CONSOLE);
        label_joystick_left_y->setObjectName(QString::fromUtf8("label_joystick_left_y"));
        label_joystick_left_y->setGeometry(QRect(183, 585, 19, 19));
        label_joystick_left_y->setFont(font1);
        label_joystick_left_y->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        label_joystick_left_x = new QLabel(TAB_CONSOLE);
        label_joystick_left_x->setObjectName(QString::fromUtf8("label_joystick_left_x"));
        label_joystick_left_x->setGeometry(QRect(79, 585, 19, 19));
        label_joystick_left_x->setFont(font1);
        label_joystick_left_x->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        LE_JOYSTICK_LT = new QLineEdit(TAB_CONSOLE);
        LE_JOYSTICK_LT->setObjectName(QString::fromUtf8("LE_JOYSTICK_LT"));
        LE_JOYSTICK_LT->setEnabled(false);
        LE_JOYSTICK_LT->setGeometry(QRect(111, 52, 130, 52));
        LE_JOYSTICK_LT->setFont(font9);
        LE_JOYSTICK_LT->setFrame(true);
        LE_JOYSTICK_LT->setAlignment(Qt::AlignCenter);
        LE_JOYSTICK_RT = new QLineEdit(TAB_CONSOLE);
        LE_JOYSTICK_RT->setObjectName(QString::fromUtf8("LE_JOYSTICK_RT"));
        LE_JOYSTICK_RT->setEnabled(false);
        LE_JOYSTICK_RT->setGeometry(QRect(638, 52, 130, 52));
        LE_JOYSTICK_RT->setFont(font9);
        LE_JOYSTICK_RT->setFrame(true);
        LE_JOYSTICK_RT->setAlignment(Qt::AlignCenter);
        label_joystick_right_x = new QLabel(TAB_CONSOLE);
        label_joystick_right_x->setObjectName(QString::fromUtf8("label_joystick_right_x"));
        label_joystick_right_x->setGeometry(QRect(606, 585, 19, 19));
        label_joystick_right_x->setFont(font1);
        label_joystick_right_x->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        QCP_JOYSTICK_RIGHT = new QCustomPlot(TAB_CONSOLE);
        QCP_JOYSTICK_RIGHT->setObjectName(QString::fromUtf8("QCP_JOYSTICK_RIGHT"));
        QCP_JOYSTICK_RIGHT->setGeometry(QRect(606, 384, 195, 195));
        LE_JOYSTICK_Y = new QLineEdit(TAB_CONSOLE);
        LE_JOYSTICK_Y->setObjectName(QString::fromUtf8("LE_JOYSTICK_Y"));
        LE_JOYSTICK_Y->setEnabled(false);
        LE_JOYSTICK_Y->setGeometry(QRect(677, 188, 52, 52));
        LE_JOYSTICK_Y->setFont(font9);
        LE_JOYSTICK_Y->setFrame(true);
        LE_JOYSTICK_Y->setAlignment(Qt::AlignCenter);
        LE_JOYSTICK_X = new QLineEdit(TAB_CONSOLE);
        LE_JOYSTICK_X->setObjectName(QString::fromUtf8("LE_JOYSTICK_X"));
        LE_JOYSTICK_X->setEnabled(false);
        LE_JOYSTICK_X->setGeometry(QRect(612, 253, 52, 52));
        LE_JOYSTICK_X->setFont(font9);
        LE_JOYSTICK_X->setFrame(true);
        LE_JOYSTICK_X->setAlignment(Qt::AlignCenter);
        LE_JOYSTICK_LEFT_Y = new QLineEdit(TAB_CONSOLE);
        LE_JOYSTICK_LEFT_Y->setObjectName(QString::fromUtf8("LE_JOYSTICK_LEFT_Y"));
        LE_JOYSTICK_LEFT_Y->setEnabled(false);
        LE_JOYSTICK_LEFT_Y->setGeometry(QRect(202, 585, 71, 19));
        LE_JOYSTICK_LEFT_Y->setMinimumSize(QSize(0, 0));
        LE_JOYSTICK_LEFT_Y->setMaximumSize(QSize(580, 200));
        LE_JOYSTICK_LEFT_Y->setFont(font1);
        LE_JOYSTICK_LEFT_Y->setAlignment(Qt::AlignCenter);
        LE_JOYSTICK_START = new QLineEdit(TAB_CONSOLE);
        LE_JOYSTICK_START->setObjectName(QString::fromUtf8("LE_JOYSTICK_START"));
        LE_JOYSTICK_START->setEnabled(false);
        LE_JOYSTICK_START->setGeometry(QRect(547, 208, 26, 58));
        LE_JOYSTICK_START->setFont(font9);
        LE_JOYSTICK_START->setFrame(true);
        LE_JOYSTICK_START->setAlignment(Qt::AlignCenter);
        LE_JOYSTICK_RIGHT_X = new QLineEdit(TAB_CONSOLE);
        LE_JOYSTICK_RIGHT_X->setObjectName(QString::fromUtf8("LE_JOYSTICK_RIGHT_X"));
        LE_JOYSTICK_RIGHT_X->setEnabled(false);
        LE_JOYSTICK_RIGHT_X->setGeometry(QRect(625, 585, 71, 19));
        LE_JOYSTICK_RIGHT_X->setMinimumSize(QSize(0, 0));
        LE_JOYSTICK_RIGHT_X->setMaximumSize(QSize(580, 200));
        LE_JOYSTICK_RIGHT_X->setFont(font1);
        LE_JOYSTICK_RIGHT_X->setAlignment(Qt::AlignCenter);
        LE_JOYSTICK_DOWN = new QLineEdit(TAB_CONSOLE);
        LE_JOYSTICK_DOWN->setObjectName(QString::fromUtf8("LE_JOYSTICK_DOWN"));
        LE_JOYSTICK_DOWN->setEnabled(false);
        LE_JOYSTICK_DOWN->setGeometry(QRect(149, 318, 52, 52));
        LE_JOYSTICK_DOWN->setFont(font9);
        LE_JOYSTICK_DOWN->setFrame(true);
        LE_JOYSTICK_DOWN->setAlignment(Qt::AlignCenter);
        LE_JOYSTICK_RB = new QLineEdit(TAB_CONSOLE);
        LE_JOYSTICK_RB->setObjectName(QString::fromUtf8("LE_JOYSTICK_RB"));
        LE_JOYSTICK_RB->setEnabled(false);
        LE_JOYSTICK_RB->setGeometry(QRect(638, 110, 130, 39));
        LE_JOYSTICK_RB->setFont(font9);
        LE_JOYSTICK_RB->setFrame(true);
        LE_JOYSTICK_RB->setAlignment(Qt::AlignCenter);
        LE_JOYSTICK_LEFT = new QLineEdit(TAB_CONSOLE);
        LE_JOYSTICK_LEFT->setObjectName(QString::fromUtf8("LE_JOYSTICK_LEFT"));
        LE_JOYSTICK_LEFT->setEnabled(false);
        LE_JOYSTICK_LEFT->setGeometry(QRect(85, 253, 52, 52));
        LE_JOYSTICK_LEFT->setFont(font9);
        LE_JOYSTICK_LEFT->setFrame(true);
        LE_JOYSTICK_LEFT->setAlignment(Qt::AlignCenter);
        LE_JOYSTICK_LEFT_X = new QLineEdit(TAB_CONSOLE);
        LE_JOYSTICK_LEFT_X->setObjectName(QString::fromUtf8("LE_JOYSTICK_LEFT_X"));
        LE_JOYSTICK_LEFT_X->setEnabled(false);
        LE_JOYSTICK_LEFT_X->setGeometry(QRect(97, 585, 71, 19));
        LE_JOYSTICK_LEFT_X->setMinimumSize(QSize(0, 0));
        LE_JOYSTICK_LEFT_X->setMaximumSize(QSize(580, 200));
        LE_JOYSTICK_LEFT_X->setFont(font1);
        LE_JOYSTICK_LEFT_X->setAlignment(Qt::AlignCenter);
        LE_CONSOLE_NAME = new QLineEdit(TAB_CONSOLE);
        LE_CONSOLE_NAME->setObjectName(QString::fromUtf8("LE_CONSOLE_NAME"));
        LE_CONSOLE_NAME->setGeometry(QRect(131, 11, 84, 19));
        LE_CONSOLE_NAME->setMouseTracking(false);
        LE_CONSOLE_NAME->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        LE_CONSOLE_NAME->setReadOnly(true);
        LE_CONSOLE_NAME_2 = new QLineEdit(TAB_CONSOLE);
        LE_CONSOLE_NAME_2->setObjectName(QString::fromUtf8("LE_CONSOLE_NAME_2"));
        LE_CONSOLE_NAME_2->setGeometry(QRect(222, 11, 520, 19));
        LE_CONSOLE_NAME_2->setMouseTracking(false);
        LE_CONSOLE_NAME_2->setReadOnly(true);
        TW_MAIN->addTab(TAB_CONSOLE, QString());
        WG_TOP = new QWidget(centralwidget);
        WG_TOP->setObjectName(QString::fromUtf8("WG_TOP"));
        WG_TOP->setGeometry(QRect(6, 0, 1261, 97));
        BT_QUIT = new QPushButton(WG_TOP);
        BT_QUIT->setObjectName(QString::fromUtf8("BT_QUIT"));
        BT_QUIT->setGeometry(QRect(1189, 16, 65, 65));
        BT_QUIT->setMinimumSize(QSize(0, 0));
        BT_QUIT->setMaximumSize(QSize(200, 200));
        QPalette palette;
        QBrush brush(QColor(0, 0, 0, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush1(QColor(239, 41, 41, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush1);
        QBrush brush2(QColor(255, 147, 147, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Light, brush2);
        QBrush brush3(QColor(247, 94, 94, 255));
        brush3.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Midlight, brush3);
        QBrush brush4(QColor(119, 20, 20, 255));
        brush4.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Dark, brush4);
        QBrush brush5(QColor(159, 27, 27, 255));
        brush5.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Active, QPalette::Text, brush);
        QBrush brush6(QColor(255, 255, 255, 255));
        brush6.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette.setBrush(QPalette::Active, QPalette::Window, brush1);
        palette.setBrush(QPalette::Active, QPalette::Shadow, brush);
        QBrush brush7(QColor(247, 148, 148, 255));
        brush7.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::AlternateBase, brush7);
        QBrush brush8(QColor(255, 255, 220, 255));
        brush8.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
        QBrush brush9(QColor(0, 0, 0, 128));
        brush9.setStyle(Qt::SolidPattern);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette::Active, QPalette::PlaceholderText, brush9);
#endif
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Light, brush2);
        palette.setBrush(QPalette::Inactive, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Inactive, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Inactive, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette.setBrush(QPalette::Inactive, QPalette::Window, brush1);
        palette.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush7);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush9);
#endif
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Light, brush2);
        palette.setBrush(QPalette::Disabled, QPalette::Midlight, brush3);
        palette.setBrush(QPalette::Disabled, QPalette::Dark, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Mid, brush5);
        palette.setBrush(QPalette::Disabled, QPalette::Text, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette.setBrush(QPalette::Disabled, QPalette::ButtonText, brush4);
        palette.setBrush(QPalette::Disabled, QPalette::Base, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Window, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush1);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush9);
#endif
        BT_QUIT->setPalette(palette);
        QFont font10;
        font10.setFamily(QString::fromUtf8("Serif"));
        font10.setPointSize(30);
        BT_QUIT->setFont(font10);
        BT_SCALE_UP = new QPushButton(WG_TOP);
        BT_SCALE_UP->setObjectName(QString::fromUtf8("BT_SCALE_UP"));
        BT_SCALE_UP->setGeometry(QRect(1118, 16, 65, 65));
        BT_SCALE_UP->setMinimumSize(QSize(0, 0));
        BT_SCALE_UP->setMaximumSize(QSize(200, 200));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush10(QColor(114, 159, 207, 255));
        brush10.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Button, brush10);
        QBrush brush11(QColor(196, 225, 255, 255));
        brush11.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Light, brush11);
        QBrush brush12(QColor(155, 192, 231, 255));
        brush12.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Midlight, brush12);
        QBrush brush13(QColor(57, 79, 103, 255));
        brush13.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Dark, brush13);
        QBrush brush14(QColor(76, 106, 138, 255));
        brush14.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::Mid, brush14);
        palette1.setBrush(QPalette::Active, QPalette::Text, brush);
        palette1.setBrush(QPalette::Active, QPalette::BrightText, brush6);
        palette1.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette1.setBrush(QPalette::Active, QPalette::Window, brush10);
        palette1.setBrush(QPalette::Active, QPalette::Shadow, brush);
        QBrush brush15(QColor(184, 207, 231, 255));
        brush15.setStyle(Qt::SolidPattern);
        palette1.setBrush(QPalette::Active, QPalette::AlternateBase, brush15);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipBase, brush8);
        palette1.setBrush(QPalette::Active, QPalette::ToolTipText, brush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette::Active, QPalette::PlaceholderText, brush9);
#endif
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Button, brush10);
        palette1.setBrush(QPalette::Inactive, QPalette::Light, brush11);
        palette1.setBrush(QPalette::Inactive, QPalette::Midlight, brush12);
        palette1.setBrush(QPalette::Inactive, QPalette::Dark, brush13);
        palette1.setBrush(QPalette::Inactive, QPalette::Mid, brush14);
        palette1.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::BrightText, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette1.setBrush(QPalette::Inactive, QPalette::Window, brush10);
        palette1.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::AlternateBase, brush15);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipBase, brush8);
        palette1.setBrush(QPalette::Inactive, QPalette::ToolTipText, brush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush9);
#endif
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush13);
        palette1.setBrush(QPalette::Disabled, QPalette::Button, brush10);
        palette1.setBrush(QPalette::Disabled, QPalette::Light, brush11);
        palette1.setBrush(QPalette::Disabled, QPalette::Midlight, brush12);
        palette1.setBrush(QPalette::Disabled, QPalette::Dark, brush13);
        palette1.setBrush(QPalette::Disabled, QPalette::Mid, brush14);
        palette1.setBrush(QPalette::Disabled, QPalette::Text, brush13);
        palette1.setBrush(QPalette::Disabled, QPalette::BrightText, brush6);
        palette1.setBrush(QPalette::Disabled, QPalette::ButtonText, brush13);
        palette1.setBrush(QPalette::Disabled, QPalette::Base, brush10);
        palette1.setBrush(QPalette::Disabled, QPalette::Window, brush10);
        palette1.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::AlternateBase, brush10);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipBase, brush8);
        palette1.setBrush(QPalette::Disabled, QPalette::ToolTipText, brush);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette1.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush9);
#endif
        BT_SCALE_UP->setPalette(palette1);
        QFont font11;
        font11.setFamily(QString::fromUtf8("Tlwg Typist"));
        font11.setPointSize(30);
        BT_SCALE_UP->setFont(font11);
        BT_MINIMIZE = new QPushButton(WG_TOP);
        BT_MINIMIZE->setObjectName(QString::fromUtf8("BT_MINIMIZE"));
        BT_MINIMIZE->setGeometry(QRect(1046, 16, 65, 65));
        BT_MINIMIZE->setMinimumSize(QSize(0, 0));
        BT_MINIMIZE->setMaximumSize(QSize(200, 200));
        BT_MINIMIZE->setFont(font11);
        WG_ROBOT_STATE = new QWidget(WG_TOP);
        WG_ROBOT_STATE->setObjectName(QString::fromUtf8("WG_ROBOT_STATE"));
        WG_ROBOT_STATE->setGeometry(QRect(5, 5, 363, 84));
        FR_ROBOT_STATE = new QFrame(WG_ROBOT_STATE);
        FR_ROBOT_STATE->setObjectName(QString::fromUtf8("FR_ROBOT_STATE"));
        FR_ROBOT_STATE->setGeometry(QRect(6, 6, 351, 78));
        FR_ROBOT_STATE->setFrameShape(QFrame::StyledPanel);
        FR_ROBOT_STATE->setFrameShadow(QFrame::Raised);
        GB_ROBOR_STATE = new QGroupBox(FR_ROBOT_STATE);
        GB_ROBOR_STATE->setObjectName(QString::fromUtf8("GB_ROBOR_STATE"));
        GB_ROBOR_STATE->setGeometry(QRect(13, 0, 338, 78));
        QFont font12;
        font12.setPointSize(10);
        font12.setBold(true);
        font12.setWeight(75);
        GB_ROBOR_STATE->setFont(font12);
        LE_CONNECT_1 = new QLineEdit(GB_ROBOR_STATE);
        LE_CONNECT_1->setObjectName(QString::fromUtf8("LE_CONNECT_1"));
        LE_CONNECT_1->setGeometry(QRect(109, 6, 221, 6));
        LE_CONNECT_1->setMouseTracking(false);
        LE_CONNECT_1->setReadOnly(true);
        LE_ROBOT_STATE = new QLineEdit(GB_ROBOR_STATE);
        LE_ROBOT_STATE->setObjectName(QString::fromUtf8("LE_ROBOT_STATE"));
        LE_ROBOT_STATE->setGeometry(QRect(0, 19, 332, 54));
        QSizePolicy sizePolicy1(QSizePolicy::Fixed, QSizePolicy::Fixed);
        sizePolicy1.setHorizontalStretch(0);
        sizePolicy1.setVerticalStretch(0);
        sizePolicy1.setHeightForWidth(LE_ROBOT_STATE->sizePolicy().hasHeightForWidth());
        LE_ROBOT_STATE->setSizePolicy(sizePolicy1);
        QFont font13;
        font13.setPointSize(27);
        font13.setBold(true);
        font13.setItalic(false);
        font13.setUnderline(false);
        font13.setWeight(75);
        LE_ROBOT_STATE->setFont(font13);
        LE_ROBOT_STATE->setCursor(QCursor(Qt::ArrowCursor));
        LE_ROBOT_STATE->setMouseTracking(false);
        LE_ROBOT_STATE->setLayoutDirection(Qt::LeftToRight);
        LE_ROBOT_STATE->setAutoFillBackground(false);
        LE_ROBOT_STATE->setFrame(true);
        LE_ROBOT_STATE->setReadOnly(true);
        LE_CONNECT_2 = new QLineEdit(FR_ROBOT_STATE);
        LE_CONNECT_2->setObjectName(QString::fromUtf8("LE_CONNECT_2"));
        LE_CONNECT_2->setGeometry(QRect(2, 2, 6, 71));
        LE_CONNECT_2->setMouseTracking(false);
        LE_CONNECT_2->setReadOnly(true);
        LB_IMG_CAMEL = new QLabel(WG_TOP);
        LB_IMG_CAMEL->setObjectName(QString::fromUtf8("LB_IMG_CAMEL"));
        LB_IMG_CAMEL->setGeometry(QRect(786, 17, 247, 65));
        BT_ROBOT_START = new QPushButton(WG_TOP);
        BT_ROBOT_START->setObjectName(QString::fromUtf8("BT_ROBOT_START"));
        BT_ROBOT_START->setGeometry(QRect(394, 10, 123, 78));
        QFont font14;
        font14.setPointSize(15);
        font14.setBold(false);
        font14.setUnderline(false);
        font14.setWeight(50);
        BT_ROBOT_START->setFont(font14);
        BT_ROBOT_START->setCheckable(false);
        GB_GRAPH_OPTION = new QGroupBox(WG_TOP);
        GB_GRAPH_OPTION->setObjectName(QString::fromUtf8("GB_GRAPH_OPTION"));
        GB_GRAPH_OPTION->setGeometry(QRect(551, 10, 221, 78));
        GB_GRAPH_OPTION->setFont(font6);
        BT_GRAPH_RESET = new QPushButton(GB_GRAPH_OPTION);
        BT_GRAPH_RESET->setObjectName(QString::fromUtf8("BT_GRAPH_RESET"));
        BT_GRAPH_RESET->setGeometry(QRect(6, 32, 65, 39));
        BT_GRAPH_RESET->setFont(font2);
        BT_GRAPH_UP = new QPushButton(GB_GRAPH_OPTION);
        BT_GRAPH_UP->setObjectName(QString::fromUtf8("BT_GRAPH_UP"));
        BT_GRAPH_UP->setGeometry(QRect(136, 32, 39, 39));
        QFont font15;
        font15.setPointSize(15);
        font15.setBold(true);
        font15.setWeight(75);
        BT_GRAPH_UP->setFont(font15);
        BT_GRAPH_DOWN = new QPushButton(GB_GRAPH_OPTION);
        BT_GRAPH_DOWN->setObjectName(QString::fromUtf8("BT_GRAPH_DOWN"));
        BT_GRAPH_DOWN->setGeometry(QRect(175, 32, 39, 39));
        BT_GRAPH_DOWN->setFont(font15);
        BT_GRAPH_PAUSE_GRAPH = new QPushButton(GB_GRAPH_OPTION);
        BT_GRAPH_PAUSE_GRAPH->setObjectName(QString::fromUtf8("BT_GRAPH_PAUSE_GRAPH"));
        BT_GRAPH_PAUSE_GRAPH->setGeometry(QRect(71, 32, 65, 39));
        BT_GRAPH_PAUSE_GRAPH->setFont(font2);
        GB_CONTROL_BT = new QGroupBox(centralwidget);
        GB_CONTROL_BT->setObjectName(QString::fromUtf8("GB_CONTROL_BT"));
        GB_CONTROL_BT->setGeometry(QRect(10, 100, 372, 651));
        GB_CONTROL_BT->setFont(font4);
        GB_HOME_MOTION = new QGroupBox(GB_CONTROL_BT);
        GB_HOME_MOTION->setObjectName(QString::fromUtf8("GB_HOME_MOTION"));
        GB_HOME_MOTION->setGeometry(QRect(10, 32, 351, 136));
        QFont font16;
        font16.setPointSize(9);
        font16.setBold(false);
        font16.setItalic(false);
        font16.setUnderline(false);
        font16.setWeight(50);
        GB_HOME_MOTION->setFont(font16);
        BT_SIT_DOWN = new QPushButton(GB_HOME_MOTION);
        BT_SIT_DOWN->setObjectName(QString::fromUtf8("BT_SIT_DOWN"));
        BT_SIT_DOWN->setGeometry(QRect(181, 26, 162, 97));
        QFont font17;
        font17.setPointSize(15);
        font17.setBold(false);
        font17.setItalic(false);
        font17.setUnderline(false);
        font17.setWeight(50);
        BT_SIT_DOWN->setFont(font17);
        BT_STAND_UP = new QPushButton(GB_HOME_MOTION);
        BT_STAND_UP->setObjectName(QString::fromUtf8("BT_STAND_UP"));
        BT_STAND_UP->setGeometry(QRect(5, 26, 162, 97));
        BT_STAND_UP->setFont(font17);
        GB_TROT_MODE = new QGroupBox(GB_CONTROL_BT);
        GB_TROT_MODE->setObjectName(QString::fromUtf8("GB_TROT_MODE"));
        GB_TROT_MODE->setGeometry(QRect(10, 182, 350, 273));
        GB_TROT_MODE->setFont(font16);
        LE_TROT_OVERLAP = new QLineEdit(GB_TROT_MODE);
        LE_TROT_OVERLAP->setObjectName(QString::fromUtf8("LE_TROT_OVERLAP"));
        LE_TROT_OVERLAP->setEnabled(false);
        LE_TROT_OVERLAP->setGeometry(QRect(266, 26, 52, 6));
        LE_TROT_OVERLAP->setMouseTracking(false);
        LE_TROT_OVERLAP->setText(QString::fromUtf8(""));
        BT_TROT_SLOW = new QPushButton(GB_TROT_MODE);
        BT_TROT_SLOW->setObjectName(QString::fromUtf8("BT_TROT_SLOW"));
        BT_TROT_SLOW->setGeometry(QRect(6, 39, 104, 97));
        QSizePolicy sizePolicy2(QSizePolicy::Minimum, QSizePolicy::Minimum);
        sizePolicy2.setHorizontalStretch(0);
        sizePolicy2.setVerticalStretch(0);
        sizePolicy2.setHeightForWidth(BT_TROT_SLOW->sizePolicy().hasHeightForWidth());
        BT_TROT_SLOW->setSizePolicy(sizePolicy2);
        BT_TROT_SLOW->setFont(font17);
        LE_TROT_FAST = new QLineEdit(GB_TROT_MODE);
        LE_TROT_FAST->setObjectName(QString::fromUtf8("LE_TROT_FAST"));
        LE_TROT_FAST->setEnabled(false);
        LE_TROT_FAST->setGeometry(QRect(149, 26, 52, 6));
        LE_TROT_FAST->setMouseTracking(false);
        LE_TROT_SLOW = new QLineEdit(GB_TROT_MODE);
        LE_TROT_SLOW->setObjectName(QString::fromUtf8("LE_TROT_SLOW"));
        LE_TROT_SLOW->setEnabled(false);
        LE_TROT_SLOW->setGeometry(QRect(32, 26, 52, 6));
        LE_TROT_SLOW->setMouseTracking(false);
        BT_TROT_FAST = new QPushButton(GB_TROT_MODE);
        BT_TROT_FAST->setObjectName(QString::fromUtf8("BT_TROT_FAST"));
        BT_TROT_FAST->setGeometry(QRect(123, 39, 104, 97));
        sizePolicy2.setHeightForWidth(BT_TROT_FAST->sizePolicy().hasHeightForWidth());
        BT_TROT_FAST->setSizePolicy(sizePolicy2);
        BT_TROT_FAST->setFont(font17);
        BT_TROT_OVERLAP = new QPushButton(GB_TROT_MODE);
        BT_TROT_OVERLAP->setObjectName(QString::fromUtf8("BT_TROT_OVERLAP"));
        BT_TROT_OVERLAP->setGeometry(QRect(240, 39, 104, 97));
        sizePolicy2.setHeightForWidth(BT_TROT_OVERLAP->sizePolicy().hasHeightForWidth());
        BT_TROT_OVERLAP->setSizePolicy(sizePolicy2);
        BT_TROT_OVERLAP->setFont(font17);
        BT_TROT_STOP = new QPushButton(GB_TROT_MODE);
        BT_TROT_STOP->setObjectName(QString::fromUtf8("BT_TROT_STOP"));
        BT_TROT_STOP->setGeometry(QRect(19, 162, 312, 97));
        QFont font18;
        font18.setPointSize(15);
        font18.setBold(false);
        font18.setItalic(false);
        font18.setUnderline(false);
        font18.setWeight(50);
        font18.setStrikeOut(false);
        BT_TROT_STOP->setFont(font18);
        LE_TROT_STOP = new QLineEdit(GB_TROT_MODE);
        LE_TROT_STOP->setObjectName(QString::fromUtf8("LE_TROT_STOP"));
        LE_TROT_STOP->setEnabled(false);
        LE_TROT_STOP->setGeometry(QRect(130, 149, 91, 6));
        LE_TROT_STOP->setMouseTracking(false);
        BT_E_STOP = new QPushButton(GB_CONTROL_BT);
        BT_E_STOP->setObjectName(QString::fromUtf8("BT_E_STOP"));
        BT_E_STOP->setGeometry(QRect(6, 546, 360, 91));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush);
        QBrush brush16(QColor(255, 0, 0, 255));
        brush16.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Button, brush16);
        QBrush brush17(QColor(255, 127, 127, 255));
        brush17.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Light, brush17);
        QBrush brush18(QColor(255, 63, 63, 255));
        brush18.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Midlight, brush18);
        QBrush brush19(QColor(127, 0, 0, 255));
        brush19.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Dark, brush19);
        QBrush brush20(QColor(170, 0, 0, 255));
        brush20.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Mid, brush20);
        palette2.setBrush(QPalette::Active, QPalette::Text, brush);
        palette2.setBrush(QPalette::Active, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Active, QPalette::Base, brush6);
        palette2.setBrush(QPalette::Active, QPalette::Window, brush16);
        palette2.setBrush(QPalette::Active, QPalette::Shadow, brush);
        QBrush brush21(QColor(165, 205, 255, 255));
        brush21.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Highlight, brush21);
        palette2.setBrush(QPalette::Active, QPalette::HighlightedText, brush);
        QBrush brush22(QColor(9, 79, 209, 255));
        brush22.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Active, QPalette::Link, brush22);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette::Active, QPalette::PlaceholderText, brush9);
#endif
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Button, brush16);
        palette2.setBrush(QPalette::Inactive, QPalette::Light, brush17);
        palette2.setBrush(QPalette::Inactive, QPalette::Midlight, brush18);
        palette2.setBrush(QPalette::Inactive, QPalette::Dark, brush19);
        palette2.setBrush(QPalette::Inactive, QPalette::Mid, brush20);
        palette2.setBrush(QPalette::Inactive, QPalette::Text, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::ButtonText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Base, brush6);
        palette2.setBrush(QPalette::Inactive, QPalette::Window, brush16);
        palette2.setBrush(QPalette::Inactive, QPalette::Shadow, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Highlight, brush21);
        palette2.setBrush(QPalette::Inactive, QPalette::HighlightedText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::Link, brush22);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette::Inactive, QPalette::PlaceholderText, brush9);
#endif
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush19);
        palette2.setBrush(QPalette::Disabled, QPalette::Button, brush16);
        palette2.setBrush(QPalette::Disabled, QPalette::Light, brush17);
        palette2.setBrush(QPalette::Disabled, QPalette::Midlight, brush18);
        palette2.setBrush(QPalette::Disabled, QPalette::Dark, brush19);
        palette2.setBrush(QPalette::Disabled, QPalette::Mid, brush20);
        palette2.setBrush(QPalette::Disabled, QPalette::Text, brush19);
        palette2.setBrush(QPalette::Disabled, QPalette::ButtonText, brush19);
        palette2.setBrush(QPalette::Disabled, QPalette::Base, brush16);
        palette2.setBrush(QPalette::Disabled, QPalette::Window, brush16);
        palette2.setBrush(QPalette::Disabled, QPalette::Shadow, brush);
        QBrush brush23(QColor(145, 145, 145, 255));
        brush23.setStyle(Qt::SolidPattern);
        palette2.setBrush(QPalette::Disabled, QPalette::Highlight, brush23);
        palette2.setBrush(QPalette::Disabled, QPalette::HighlightedText, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::Link, brush22);
#if QT_VERSION >= QT_VERSION_CHECK(5, 12, 0)
        palette2.setBrush(QPalette::Disabled, QPalette::PlaceholderText, brush9);
#endif
        BT_E_STOP->setPalette(palette2);
        QFont font19;
        font19.setPointSize(18);
        font19.setBold(true);
        font19.setItalic(false);
        font19.setUnderline(false);
        font19.setWeight(75);
        font19.setStrikeOut(false);
        BT_E_STOP->setFont(font19);
        LE_STUMBLE = new QLineEdit(GB_CONTROL_BT);
        LE_STUMBLE->setObjectName(QString::fromUtf8("LE_STUMBLE"));
        LE_STUMBLE->setEnabled(false);
        LE_STUMBLE->setGeometry(QRect(124, 510, 120, 7));
        LE_STUMBLE->setMouseTracking(false);
        L_STUMBLE = new QLabel(GB_CONTROL_BT);
        L_STUMBLE->setObjectName(QString::fromUtf8("L_STUMBLE"));
        L_STUMBLE->setGeometry(QRect(124, 488, 120, 19));
        L_STUMBLE->setAlignment(Qt::AlignCenter);
        MainWindow->setCentralWidget(centralwidget);
        WG_TOP->raise();
        TW_MAIN->raise();
        GB_CONTROL_BT->raise();
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 1280, 22));
        MainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        MainWindow->setStatusBar(statusbar);

        retranslateUi(MainWindow);

        TW_MAIN->setCurrentIndex(0);
        GAB_FOOT_TRAJ->setCurrentIndex(0);
        tabWidget_motor->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", nullptr));
        GB_MOTOR->setTitle(QApplication::translate("MainWindow", "MOTOR", nullptr));
        QTableWidgetItem *___qtablewidgetitem = TB_MOTOR->horizontalHeaderItem(0);
        ___qtablewidgetitem->setText(QApplication::translate("MainWindow", "Error", nullptr));
        QTableWidgetItem *___qtablewidgetitem1 = TB_MOTOR->horizontalHeaderItem(1);
        ___qtablewidgetitem1->setText(QApplication::translate("MainWindow", "Temp", nullptr));
        QTableWidgetItem *___qtablewidgetitem2 = TB_MOTOR->horizontalHeaderItem(2);
        ___qtablewidgetitem2->setText(QApplication::translate("MainWindow", "Voltage", nullptr));
        QTableWidgetItem *___qtablewidgetitem3 = TB_MOTOR->horizontalHeaderItem(3);
        ___qtablewidgetitem3->setText(QApplication::translate("MainWindow", "Motor\n"
"Angle", nullptr));
        QTableWidgetItem *___qtablewidgetitem4 = TB_MOTOR->horizontalHeaderItem(4);
        ___qtablewidgetitem4->setText(QApplication::translate("MainWindow", "Desired\n"
"Torque", nullptr));
        QTableWidgetItem *___qtablewidgetitem5 = TB_MOTOR->horizontalHeaderItem(5);
        ___qtablewidgetitem5->setText(QApplication::translate("MainWindow", "Motor\n"
"Torque", nullptr));
        QTableWidgetItem *___qtablewidgetitem6 = TB_MOTOR->verticalHeaderItem(0);
        ___qtablewidgetitem6->setText(QApplication::translate("MainWindow", " FLHR", nullptr));
        QTableWidgetItem *___qtablewidgetitem7 = TB_MOTOR->verticalHeaderItem(1);
        ___qtablewidgetitem7->setText(QApplication::translate("MainWindow", " FLHP", nullptr));
        QTableWidgetItem *___qtablewidgetitem8 = TB_MOTOR->verticalHeaderItem(2);
        ___qtablewidgetitem8->setText(QApplication::translate("MainWindow", " FLKP", nullptr));
        QTableWidgetItem *___qtablewidgetitem9 = TB_MOTOR->verticalHeaderItem(3);
        ___qtablewidgetitem9->setText(QApplication::translate("MainWindow", " FRHR", nullptr));
        QTableWidgetItem *___qtablewidgetitem10 = TB_MOTOR->verticalHeaderItem(4);
        ___qtablewidgetitem10->setText(QApplication::translate("MainWindow", " FRHP", nullptr));
        QTableWidgetItem *___qtablewidgetitem11 = TB_MOTOR->verticalHeaderItem(5);
        ___qtablewidgetitem11->setText(QApplication::translate("MainWindow", " FRKP", nullptr));
        QTableWidgetItem *___qtablewidgetitem12 = TB_MOTOR->verticalHeaderItem(6);
        ___qtablewidgetitem12->setText(QApplication::translate("MainWindow", " HLHR", nullptr));
        QTableWidgetItem *___qtablewidgetitem13 = TB_MOTOR->verticalHeaderItem(7);
        ___qtablewidgetitem13->setText(QApplication::translate("MainWindow", " HLHP", nullptr));
        QTableWidgetItem *___qtablewidgetitem14 = TB_MOTOR->verticalHeaderItem(8);
        ___qtablewidgetitem14->setText(QApplication::translate("MainWindow", " HLKP", nullptr));
        QTableWidgetItem *___qtablewidgetitem15 = TB_MOTOR->verticalHeaderItem(9);
        ___qtablewidgetitem15->setText(QApplication::translate("MainWindow", " HRHR", nullptr));
        QTableWidgetItem *___qtablewidgetitem16 = TB_MOTOR->verticalHeaderItem(10);
        ___qtablewidgetitem16->setText(QApplication::translate("MainWindow", " HRHP", nullptr));
        QTableWidgetItem *___qtablewidgetitem17 = TB_MOTOR->verticalHeaderItem(11);
        ___qtablewidgetitem17->setText(QApplication::translate("MainWindow", " HRKP", nullptr));

        const bool __sortingEnabled = TB_MOTOR->isSortingEnabled();
        TB_MOTOR->setSortingEnabled(false);
        TB_MOTOR->setSortingEnabled(__sortingEnabled);

        GB_IMU->setTitle(QApplication::translate("MainWindow", "IMU", nullptr));
        QTableWidgetItem *___qtablewidgetitem18 = TW_IMU_RPY->horizontalHeaderItem(0);
        ___qtablewidgetitem18->setText(QApplication::translate("MainWindow", "ROLL", nullptr));
        QTableWidgetItem *___qtablewidgetitem19 = TW_IMU_RPY->horizontalHeaderItem(1);
        ___qtablewidgetitem19->setText(QApplication::translate("MainWindow", "PITCH", nullptr));
        QTableWidgetItem *___qtablewidgetitem20 = TW_IMU_RPY->horizontalHeaderItem(2);
        ___qtablewidgetitem20->setText(QApplication::translate("MainWindow", "YAW", nullptr));
        QTableWidgetItem *___qtablewidgetitem21 = TW_IMU_RPY->verticalHeaderItem(0);
        ___qtablewidgetitem21->setText(QApplication::translate("MainWindow", "  RPY  ", nullptr));
        QTableWidgetItem *___qtablewidgetitem22 = TW_IMU_GYRO->horizontalHeaderItem(0);
        ___qtablewidgetitem22->setText(QApplication::translate("MainWindow", "X", nullptr));
        QTableWidgetItem *___qtablewidgetitem23 = TW_IMU_GYRO->horizontalHeaderItem(1);
        ___qtablewidgetitem23->setText(QApplication::translate("MainWindow", "Y", nullptr));
        QTableWidgetItem *___qtablewidgetitem24 = TW_IMU_GYRO->horizontalHeaderItem(2);
        ___qtablewidgetitem24->setText(QApplication::translate("MainWindow", "Z", nullptr));
        QTableWidgetItem *___qtablewidgetitem25 = TW_IMU_GYRO->verticalHeaderItem(0);
        ___qtablewidgetitem25->setText(QApplication::translate("MainWindow", " GYRO", nullptr));
        QTableWidgetItem *___qtablewidgetitem26 = TW_IMU_ACC->horizontalHeaderItem(0);
        ___qtablewidgetitem26->setText(QApplication::translate("MainWindow", "X", nullptr));
        QTableWidgetItem *___qtablewidgetitem27 = TW_IMU_ACC->horizontalHeaderItem(1);
        ___qtablewidgetitem27->setText(QApplication::translate("MainWindow", "Y", nullptr));
        QTableWidgetItem *___qtablewidgetitem28 = TW_IMU_ACC->horizontalHeaderItem(2);
        ___qtablewidgetitem28->setText(QApplication::translate("MainWindow", "Z", nullptr));
        QTableWidgetItem *___qtablewidgetitem29 = TW_IMU_ACC->verticalHeaderItem(0);
        ___qtablewidgetitem29->setText(QApplication::translate("MainWindow", "  ACC  ", nullptr));
        GB_IP_ADDRESS->setTitle(QApplication::translate("MainWindow", "ROBOT IP ADDRESS", nullptr));
        TE_IP_ADDRESS->setText(QApplication::translate("MainWindow", "192.168.0.10", nullptr));
        BT_IP_ADDRESS->setText(QApplication::translate("MainWindow", "Connect", nullptr));
        LB_IP_ADDRESS->setText(QString());
        GB_RESTART->setTitle(QApplication::translate("MainWindow", "ROBOT PROCESS", nullptr));
        BT_ROBOT_RESTART->setText(QApplication::translate("MainWindow", "RESTART", nullptr));
        CB_DEVELOPER_MODE->setText(QApplication::translate("MainWindow", "ENABLE\n"
"DEVELOPER\n"
"MODE", nullptr));
        TW_MAIN->setTabText(TW_MAIN->indexOf(TAB_ROBOT), QApplication::translate("MainWindow", "ROBOT", nullptr));
        GAB_FOOT_TRAJ->setTabText(GAB_FOOT_TRAJ->indexOf(TAB_LINEAR), QApplication::translate("MainWindow", "LINEAR", nullptr));
        GAB_FOOT_TRAJ->setTabText(GAB_FOOT_TRAJ->indexOf(TAB_ANGULAR), QApplication::translate("MainWindow", "ANGULAR", nullptr));
        LE_HIP_ROLL->setText(QApplication::translate("MainWindow", "HIP ROLL", nullptr));
        LE_HIP_PITCH->setText(QApplication::translate("MainWindow", "HIP PITCH", nullptr));
        LE_KNEE_PITCH->setText(QApplication::translate("MainWindow", "KNEE PITCH", nullptr));
        LE_FL->setText(QApplication::translate("MainWindow", "FL", nullptr));
        LE_FR->setText(QApplication::translate("MainWindow", "FR", nullptr));
        LE_HL->setText(QApplication::translate("MainWindow", "HL", nullptr));
        LE_HR->setText(QApplication::translate("MainWindow", "HR", nullptr));
        tabWidget_motor->setTabText(tabWidget_motor->indexOf(tab_motor_position), QApplication::translate("MainWindow", "Position", nullptr));
        LE_HIP_ROLL_2->setText(QApplication::translate("MainWindow", "HIP ROLL", nullptr));
        LE_FL_2->setText(QApplication::translate("MainWindow", "FL", nullptr));
        LE_HR_2->setText(QApplication::translate("MainWindow", "HR", nullptr));
        LE_HL_2->setText(QApplication::translate("MainWindow", "HL", nullptr));
        LE_FR_2->setText(QApplication::translate("MainWindow", "FR", nullptr));
        LE_HIP_PITCH_2->setText(QApplication::translate("MainWindow", "HIP PITCH", nullptr));
        LE_KNEE_PITCH_2->setText(QApplication::translate("MainWindow", "KNEE PITCH", nullptr));
        tabWidget_motor->setTabText(tabWidget_motor->indexOf(tab_motor_velocity), QApplication::translate("MainWindow", "Velocity", nullptr));
        LE_KNEE_PITCH_3->setText(QApplication::translate("MainWindow", "KNEE PITCH", nullptr));
        LE_HR_3->setText(QApplication::translate("MainWindow", "HR", nullptr));
        LE_FL_3->setText(QApplication::translate("MainWindow", "FL", nullptr));
        LE_HIP_PITCH_3->setText(QApplication::translate("MainWindow", "HIP PITCH", nullptr));
        LE_HIP_ROLL_3->setText(QApplication::translate("MainWindow", "HIP ROLL", nullptr));
        LE_FR_3->setText(QApplication::translate("MainWindow", "FR", nullptr));
        LE_HL_3->setText(QApplication::translate("MainWindow", "HL", nullptr));
        tabWidget_motor->setTabText(tabWidget_motor->indexOf(tab_motor_torque), QApplication::translate("MainWindow", "Torque", nullptr));
        GAB_FOOT_TRAJ->setTabText(GAB_FOOT_TRAJ->indexOf(TAB_MOTOR), QApplication::translate("MainWindow", "MOTOR", nullptr));
        GAB_FOOT_TRAJ->setTabText(GAB_FOOT_TRAJ->indexOf(TAB_CONTACT), QApplication::translate("MainWindow", "CONTACT", nullptr));
        TW_MAIN->setTabText(TW_MAIN->indexOf(TAB_CONTROL), QApplication::translate("MainWindow", "STATUS", nullptr));
        LE_JOYSTICK_LB->setText(QApplication::translate("MainWindow", "LB", nullptr));
        label_joystick_right_y->setText(QApplication::translate("MainWindow", "Y : ", nullptr));
        LE_JOYSTICK_UP->setText(QApplication::translate("MainWindow", "\342\206\221", nullptr));
        LE_JOYSTICK_B->setText(QApplication::translate("MainWindow", "B", nullptr));
        LE_JOYSTICK_RIGHT->setText(QApplication::translate("MainWindow", "\342\206\222", nullptr));
        LE_JOYSTICK_A->setText(QApplication::translate("MainWindow", "A", nullptr));
        LE_JOYSTICK_RIGHT_Y->setText(QString());
        label_joystick_left_y->setText(QApplication::translate("MainWindow", "Y : ", nullptr));
        label_joystick_left_x->setText(QApplication::translate("MainWindow", "X : ", nullptr));
        LE_JOYSTICK_LT->setText(QApplication::translate("MainWindow", "LT", nullptr));
        LE_JOYSTICK_RT->setText(QApplication::translate("MainWindow", "RT", nullptr));
        label_joystick_right_x->setText(QApplication::translate("MainWindow", "X : ", nullptr));
        LE_JOYSTICK_Y->setText(QApplication::translate("MainWindow", "Y", nullptr));
        LE_JOYSTICK_X->setText(QApplication::translate("MainWindow", "X", nullptr));
        LE_JOYSTICK_LEFT_Y->setText(QString());
        LE_JOYSTICK_START->setText(QApplication::translate("MainWindow", "\342\211\241", nullptr));
        LE_JOYSTICK_RIGHT_X->setText(QString());
        LE_JOYSTICK_DOWN->setText(QApplication::translate("MainWindow", "\342\206\223", nullptr));
        LE_JOYSTICK_RB->setText(QApplication::translate("MainWindow", "RB", nullptr));
        LE_JOYSTICK_LEFT->setText(QApplication::translate("MainWindow", "\342\206\220", nullptr));
        LE_JOYSTICK_LEFT_X->setText(QString());
        LE_CONSOLE_NAME->setText(QApplication::translate("MainWindow", "Console : ", nullptr));
        LE_CONSOLE_NAME_2->setText(QString());
        TW_MAIN->setTabText(TW_MAIN->indexOf(TAB_CONSOLE), QApplication::translate("MainWindow", "CONSOLE", nullptr));
        BT_QUIT->setText(QApplication::translate("MainWindow", "\342\234\225", nullptr));
        BT_SCALE_UP->setText(QApplication::translate("MainWindow", "\342\226\241", nullptr));
        BT_MINIMIZE->setText(QApplication::translate("MainWindow", "_", nullptr));
        GB_ROBOR_STATE->setTitle(QApplication::translate("MainWindow", "ROBOT STATE", nullptr));
        LE_ROBOT_STATE->setText(QApplication::translate("MainWindow", "DISCONNECTED", nullptr));
        LB_IMG_CAMEL->setText(QString());
        BT_ROBOT_START->setText(QApplication::translate("MainWindow", "AUTO\n"
"START", nullptr));
        GB_GRAPH_OPTION->setTitle(QApplication::translate("MainWindow", "GRAPH-OPTION", nullptr));
        BT_GRAPH_RESET->setText(QApplication::translate("MainWindow", "RESET\n"
"GRAPH", nullptr));
        BT_GRAPH_UP->setText(QApplication::translate("MainWindow", "\342\226\262", nullptr));
        BT_GRAPH_DOWN->setText(QApplication::translate("MainWindow", "\342\226\274", nullptr));
        BT_GRAPH_PAUSE_GRAPH->setText(QApplication::translate("MainWindow", "PAUSE\n"
"GRAPH", nullptr));
        GB_CONTROL_BT->setTitle(QApplication::translate("MainWindow", "MOTION CONTROL", nullptr));
        GB_HOME_MOTION->setTitle(QApplication::translate("MainWindow", "HOME MOTION", nullptr));
        BT_SIT_DOWN->setText(QApplication::translate("MainWindow", "SIT\n"
"DOWN", nullptr));
        BT_STAND_UP->setText(QApplication::translate("MainWindow", "STAND\n"
"UP", nullptr));
        GB_TROT_MODE->setTitle(QApplication::translate("MainWindow", "WALKING MOTION", nullptr));
        BT_TROT_SLOW->setText(QApplication::translate("MainWindow", "TROT\n"
"SLOW", nullptr));
        LE_TROT_FAST->setText(QString());
        LE_TROT_SLOW->setText(QString());
        BT_TROT_FAST->setText(QApplication::translate("MainWindow", "TROT\n"
"FAST", nullptr));
        BT_TROT_OVERLAP->setText(QApplication::translate("MainWindow", "TROT\n"
"OVERLAP", nullptr));
        BT_TROT_STOP->setText(QApplication::translate("MainWindow", "TROT\n"
"STOP", nullptr));
        LE_TROT_STOP->setText(QString());
        BT_E_STOP->setText(QApplication::translate("MainWindow", "EMERGENCY\n"
"STOP", nullptr));
        LE_STUMBLE->setText(QString());
        L_STUMBLE->setText(QApplication::translate("MainWindow", "STUMBLE", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // MAINWINDOWPTOEFP_H
