//
// Created by camel on 22. 9. 21.
//

#ifndef RAISIM_ROBOTDESCRIPTION_H
#define RAISIM_ROBOTDESCRIPTION_H


enum LEG_INDEX
{
    FL_IDX = 0,
    FR_IDX,
    HL_IDX,
    HR_IDX
};

enum COMMAND
{
    NO_ACT,
    MOTOR_START,
    MOTOR_OFF,
    HOME,
    READY,
    CUSTOM_1,
    CUSTOM_2,
    CHANGE_GAIT_STAND,
    CHANGE_GAIT_TROT_SLOW,
    CHANGE_GAIT_TROT_FAST,
    CHANGE_GAIT_OVERLAP_TROT_FAST,
    EMERGENCY_STOP,
    RESTART,
};

enum LOW_CONTROL_STATE
{
    STATE_LOW_CONTROL_STOP,
    STATE_LOW_CONTROL_START,
    STATE_LOW_HOME_STAND_UP_READY,
    STATE_LOW_HOME_STAND_DOWN_READY,
    STATE_LOW_HOME_CONTROL,
    STATE_LOW_BACK_FLIP_READY,
    STATE_LOW_BACK_FLIP_CONTROL,
    STATE_LOW_RECOVERY_READY,
    STATE_LOW_RECOVERY_CONTROL,
    STATE_LOW_E_STOP,
};

enum CAN_STATE
{
    CAN_NO_ACT,
    CAN_INIT,
    CAN_MOTOR_ON,
    CAN_MOTOR_OFF,
    CAN_SET_TORQUE,
    CAN_READ_ERROR,
    CAN_READ_ENCODER,
    CAN_MOTOR_STOP
};

enum VISUAL_STATE
{
    STATE_VISUAL_STOP,
    STATE_OPEN_RAISIM,
    STATE_UPDATE_VISUAL
};

enum GAIT_TYPE
{
    STAND = 0,
    TROT_SLOW,
    TROT_FAST,
    OVERLAP_TROT_FAST
};

enum GAIT_COMMAND
{
    DESIRED_GAIT_STAND,
    DESIRED_GAIT_TROT_SLOW,
    DESIRED_GAIT_TROT_FAST,
    DESIRED_GAIT_OVERLAP_TROT_FAST
};

enum FSM
{
    FSM_INITIAL,
    FSM_READY,
    FSM_STAND_UP,
    FSM_SIT_DOWN,
    FSM_STAND,
    FSM_TROT_STOP,
    FSM_TROT_SLOW,
    FSM_TROT_FAST,
    FSM_OVERLAP_TROT_FAST,
    FSM_EMERGENCY_STOP,
    FSM_RESTART,
};
enum MOTOR_INDEX : int
{
    FLHR_IDX = 0,
    FLHP_IDX,
    FLKP_IDX,
    FRHR_IDX,
    FRHP_IDX,
    FRKP_IDX,
    HLHR_IDX,
    HLHP_IDX,
    HLKP_IDX,
    HRHR_IDX,
    HRHP_IDX,
    HRKP_IDX,
    FLW_IDX,
    FRW_IDX,
    HLW_IDX,
    HRW_IDX
};

enum GAMEPAD_COMMAND
{
    GAMEPAD_NO_INPUT,
    GAMEPAD_START,
    GAMEPAD_EMERGENCY_STOP,
    GAMEPAD_STAND_UP,
    GAMEPAD_SIT_DOWN,
    GAMEPAD_TROT_STOP,
    GAMEPAD_TROT_SLOW,
    GAMEPAD_TROT_FAST,
    GAMEPAD_TROT_OVERLAP,
    GAMEPAD_RESTART,
};
#endif //RAISIM_ROBOTDESCRIPTION_H
