//
// Created by camel on 22. 9. 21.
//

#ifndef RAISIM_ROBOTDESCRIPTION_H
#define RAISIM_ROBOTDESCRIPTION_H

#include "EigenTypes.hpp"

enum LEG_INDEX
{
    FL_IDX = 0,
    FR_IDX,
    HL_IDX,
    HR_IDX
};

enum COMMAND
{
    NO_ACT,
    MOTOR_START,
    MOTOR_OFF,
    STAND_UP,
    SIT_DOWN,
    CHANGE_GAIT_STAND,
    CHANGE_GAIT_TROT_SLOW,
    CHANGE_GAIT_TROT_FAST,
    CHANGE_GAIT_OVERLAP_TROT_FAST,
    TROT_STOP,
    EMERGENCY_STOP,
    RESTART,
};

enum LOW_CONTROL_STATE
{
    STATE_LOW_CONTROL_STOP,
    STATE_LOW_CONTROL_START,
    STATE_LOW_HOME_STAND_UP_START,
    STATE_LOW_HOME_STAND_DOWN_START,
    STATE_LOW_HOME_CONTROL,
    STATE_LOW_RECOVERY_READY,
    STATE_LOW_RECOVERY_CONTROL,
    STATE_LOW_E_STOP,
};

enum CAN_STATE
{
    CAN_NO_ACT,
    CAN_INIT,
    CAN_MOTOR_ON,
    CAN_MOTOR_OFF,
    CAN_SET_TORQUE,
    CAN_READ_ERROR,
    CAN_READ_ENCODER,
    CAN_MOTOR_STOP
};

enum GAIT_TYPE
{
    STAND = 0,
    TROT_SLOW,
    TROT_FAST,
    OVERLAP_TROT_FAST
};

enum GAIT_COMMAND
{
    DESIRED_GAIT_STAND,
    DESIRED_GAIT_TROT_SLOW,
    DESIRED_GAIT_TROT_FAST,
    DESIRED_GAIT_OVERLAP_TROT_FAST
};

enum FSM
{
    FSM_INITIAL,
    FSM_READY,
    FSM_STAND_UP,
    FSM_SIT_DOWN,
    FSM_STAND,
    FSM_TROT_STOP,
    FSM_TROT_SLOW,
    FSM_TROT_FAST,
    FSM_OVERLAP_TROT_FAST,
    FSM_EMERGENCY_STOP,
    FSM_RESTART,
};

enum GAMEPAD_COMMAND
{
    GAMEPAD_NO_INPUT,
    GAMEPAD_START,
    GAMEPAD_EMERGENCY_STOP,
    GAMEPAD_STAND_UP,
    GAMEPAD_SIT_DOWN,
    GAMEPAD_TROT_STOP,
    GAMEPAD_TROT_SLOW,
    GAMEPAD_TROT_FAST,
    GAMEPAD_TROT_OVERLAP,
    GAMEPAD_RESTART,
};

namespace STUMBLE
{
    enum RECOVERY_STAGE
    {
        NO_ACT,
        STOPPING,
        BALANCING,
        FOOT_RECOVERY
    };
}

#endif //RAISIM_ROBOTDESCRIPTION_H
